// Versioned workout plan persistence and plan activation engine. Pure & Supabase-backed.
// 1. Versioning: Never overwrites history. Creates "Plan Name V1", "Plan Name V2", etc.
// 2. Active plan flag: Sets newly saved or explicitly requested plan as active (is_active: true)
//    while setting prior user plans to is_active: false.
// 3. Transactions: Inserts workout_plans -> plan_days -> plan_exercises.

import { GeneratedDay } from './programGenerator.ts';
import { resolveExerciseAlias } from './exerciseResolver.ts';

export interface SavePlanResult {
  success: boolean;
  planId?: string;
  planName?: string;
  version?: number;
  error?: string;
}

export interface ActivatePlanResult {
  success: boolean;
  planId?: string;
  planName?: string;
  error?: string;
}

export async function saveWorkoutPlan(
  supabase: any,
  userId: string,
  basePlanName: string,
  days: GeneratedDay[],
  description = 'Generated by Yeti AI Coach',
): Promise<SavePlanResult> {
  try {
    // 1. Query existing plans for this user to determine version
    const { data: existingPlans } = await supabase
      .from('workout_plans')
      .select('id, name, created_at')
      .eq('user_id', userId);

    const cleanBaseName = basePlanName.replace(/\s*V\d+$/i, '').trim() || 'Workout Program';
    let maxVersion = 0;

    (existingPlans || []).forEach((p: any) => {
      const match = (p.name || '').match(new RegExp(`^${cleanBaseName}(?:\\s+V(\\d+))?$`, 'i'));
      if (match) {
        const v = match[1] ? parseInt(match[1], 10) : 1;
        if (v > maxVersion) maxVersion = v;
      }
    });

    const nextVersion = maxVersion + 1;
    const versionName = `${cleanBaseName} V${nextVersion}`;

    // 2. Deactivate previous active plans for this user
    await supabase
      .from('workout_plans')
      .update({ is_active: false })
      .eq('user_id', userId)
      .eq('is_active', true);

    // 3. Create the new workout_plan
    const { data: newPlan, error: planErr } = await supabase
      .from('workout_plans')
      .insert({
        user_id: userId,
        name: versionName,
        description,
        is_active: true,
        updated_at: new Date().toISOString(),
      })
      .select('id, name')
      .single();

    if (planErr || !newPlan) {
      throw new Error(planErr?.message || 'Failed to create workout plan record');
    }

    // 4. Create plan_days and plan_exercises
    for (let i = 0; i < days.length; i++) {
      const day = days[i];
      const { data: newDay, error: dayErr } = await supabase
        .from('plan_days')
        .insert({
          plan_id: newPlan.id,
          day_number: i + 1,
          name: day.name,
          updated_at: new Date().toISOString(),
        })
        .select('id')
        .single();

      if (dayErr || !newDay) {
        throw new Error(dayErr?.message || `Failed to create day ${day.name}`);
      }

      for (let j = 0; j < day.exercises.length; j++) {
        const ex = day.exercises[j];
        const canonical = resolveExerciseAlias(ex.name);

        const { data: exMatches } = await supabase
          .from('exercises')
          .select('id')
          .ilike('name', `%${canonical}%`)
          .limit(1);

        const exerciseId = exMatches?.[0]?.id;
        if (exerciseId) {
          await supabase.from('plan_exercises').insert({
            plan_day_id: newDay.id,
            exercise_id: exerciseId,
            order_index: j,
            sets: String(ex.sets),
            reps: ex.reps,
            rest_seconds: ex.restSeconds,
            updated_at: new Date().toISOString(),
          });
        }
      }
    }

    return {
      success: true,
      planId: newPlan.id,
      planName: newPlan.name,
      version: nextVersion,
    };
  } catch (err: any) {
    return {
      success: false,
      error: err.message || 'Database error during plan persistence',
    };
  }
}

export async function activateWorkoutPlan(
  supabase: any,
  userId: string,
  targetPlanQuery: string,
): Promise<ActivatePlanResult> {
  try {
    const { data: plans } = await supabase
      .from('workout_plans')
      .select('id, name')
      .eq('user_id', userId);

    if (!plans || plans.length === 0) {
      return { success: false, error: 'No workout plans found for your account.' };
    }

    const queryLower = targetPlanQuery.toLowerCase().trim();
    const matched = plans.find(
      (p: any) => p.id === targetPlanQuery || (p.name || '').toLowerCase().includes(queryLower),
    );

    if (!matched) {
      return { success: false, error: `Could not find a plan matching "${targetPlanQuery}".` };
    }

    // Set matched plan active, others inactive
    await supabase.from('workout_plans').update({ is_active: false }).eq('user_id', userId);
    await supabase.from('workout_plans').update({ is_active: true }).eq('id', matched.id);

    return {
      success: true,
      planId: matched.id,
      planName: matched.name,
    };
  } catch (err: any) {
    return {
      success: false,
      error: err.message || 'Database error during plan activation',
    };
  }
}
