-- YETI PHASE 7 STABILIZATION

-- 1. EXERCISE LIBRARY
CREATE TABLE exercise_library (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    category TEXT NOT NULL, -- Chest, Back, Shoulders, Arms, Legs, Core, Cardio, Mobility
    primary_muscle TEXT NOT NULL,
    secondary_muscles TEXT[],
    equipment TEXT NOT NULL,
    difficulty TEXT DEFAULT 'Beginner', -- Beginner, Intermediate, Advanced
    instructions JSONB, -- { "setup": "...", "execution": "...", "common_mistakes": "..." }
    video_url TEXT,
    thumbnail_url TEXT,
    alternatives UUID[], -- array of exercise_library ids
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed a sample exercise to test the schema
INSERT INTO exercise_library (id, name, category, primary_muscle, equipment, difficulty, instructions)
VALUES (
    uuid_generate_v4(), 
    'Barbell Bench Press', 
    'Chest', 
    'Pectoralis Major', 
    'Barbell', 
    'Intermediate', 
    '{"setup": "Feet planted. Shoulder blades retracted.", "execution": "Lower bar with control. Press explosively.", "common_mistakes": "Flared elbows. Losing scapular position."}'::jsonb
);

-- 2. ADVANCED WORKOUT BUILDER UPGRADES
-- Assuming `program_template_exercises` exists, we add the new prescription columns.
ALTER TABLE program_template_exercises 
ADD COLUMN target_rpe NUMERIC,
ADD COLUMN tempo TEXT, -- e.g., '3-1-1-1'
ADD COLUMN rest_time_seconds INTEGER DEFAULT 90,
ADD COLUMN is_superset BOOLEAN DEFAULT false,
ADD COLUMN is_dropset BOOLEAN DEFAULT false,
ADD COLUMN coach_notes TEXT;

-- 3. PLATEAU SOLUTIONS (Coach Approval Workflow)
-- We add a status column to the `coach_adjustments` table created in the previous phase to support AI Pending -> Coach Approval
ALTER TABLE coach_adjustments ADD COLUMN status TEXT DEFAULT 'PENDING'; -- PENDING, APPROVED, REJECTED, MODIFIED
ALTER TABLE coach_adjustments ADD COLUMN ai_options JSONB; -- Store the multiple options generated by AI for the coach to choose from

-- Enable RLS
ALTER TABLE exercise_library ENABLE ROW LEVEL SECURITY;

-- Everyone can read the library
CREATE POLICY "Public exercise library" ON exercise_library FOR SELECT USING (true);
