-- ============================================================================
-- 20260721_exercise_metadata_and_taxonomy.sql — Step 4.3 prerequisite
-- ============================================================================
-- Populates the rich per-row metadata columns (equipment, category, difficulty,
-- target_muscle, secondary_muscles) and the exercise_taxonomy lookup table that
-- 20260719_exercise_catalog_enrichment.sql (4.2a) added but never actually filled
-- in — confirmed live: all 2,126 rows had NULL/empty values for these columns
-- and exercise_taxonomy had 0 rows before this migration.
--
-- Coverage: only the 760 `free-exercise-db`-sourced rows get equipment/category/
-- difficulty/target_muscle/secondary_muscles here, matched exactly by source_id
-- against scratch/free-exercise-db/dist/exercises.json (760/760 matched, 0
-- misses). The other 1,366 rows (omercotkd-gifs, exercisegymgifsdb) have no
-- equivalent structured metadata source — a name-based fuzzy match against
-- free-exercise-db only covers ~8-9% of them, too low-confidence to be worth
-- the risk of mismatched equipment/category data, so they're left NULL rather
-- than guessed. muscle_group and body_part already have 100% coverage from
-- 4.2a's URL-derived backfill, so muscle-group and body-part filtering still
-- works across the whole catalog — only the equipment/category/difficulty
-- filters are scoped to the ~36% of the catalog that has that data.
-- ============================================================================

-- Auto-generated backfill values for free-exercise-db rows, source_id -> (equipment, category, difficulty, target_muscle, secondary_muscles)
-- Generated from scratch/free-exercise-db/dist/exercises.json against live source_id values (760 rows)
UPDATE public.exercises e
SET
  equipment = v.equipment,
  category = v.category,
  difficulty = v.difficulty,
  target_muscle = v.target_muscle,
  secondary_muscles = v.secondary_muscles
FROM (VALUES
  ('90_90_Hamstring', 'body only', 'stretching', 'beginner', 'hamstrings', ARRAY['calves']::text[]),
  ('Ab_Crunch_Machine', 'machine', 'strength', 'intermediate', 'abdominals', ARRAY[]::text[]),
  ('Ab_Roller', 'other', 'strength', 'intermediate', 'abdominals', ARRAY['shoulders']::text[]),
  ('Adductor', 'foam roll', 'stretching', 'intermediate', 'adductors', ARRAY[]::text[]),
  ('Adductor_Groin', NULL, 'stretching', 'intermediate', 'adductors', ARRAY[]::text[]),
  ('Advanced_Kettlebell_Windmill', 'kettlebells', 'strength', 'intermediate', 'abdominals', ARRAY['glutes','hamstrings','shoulders']::text[]),
  ('All_Fours_Quad_Stretch', 'body only', 'stretching', 'intermediate', 'quadriceps', ARRAY['quadriceps']::text[]),
  ('Alternate_Hammer_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Alternate_Incline_Dumbbell_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Alternate_Leg_Diagonal_Bound', NULL, 'plyometrics', 'beginner', 'quadriceps', ARRAY['abductors','adductors','calves','glutes','hamstrings']::text[]),
  ('Alternating_Cable_Shoulder_Press', 'cable', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Alternating_Deltoid_Raise', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Alternating_Floor_Press', 'kettlebells', 'strength', 'beginner', 'chest', ARRAY['abdominals','shoulders','triceps']::text[]),
  ('Alternating_Hang_Clean', 'kettlebells', 'strength', 'intermediate', 'hamstrings', ARRAY['biceps','calves','forearms','glutes','lower back','traps']::text[]),
  ('Alternating_Kettlebell_Press', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['triceps']::text[]),
  ('Alternating_Kettlebell_Row', 'kettlebells', 'strength', 'intermediate', 'middle back', ARRAY['biceps','lats']::text[]),
  ('Alternating_Renegade_Row', 'kettlebells', 'strength', 'expert', 'middle back', ARRAY['abdominals','biceps','chest','lats','triceps']::text[]),
  ('Ankle_On_The_Knee', NULL, 'stretching', 'beginner', 'glutes', ARRAY[]::text[]),
  ('Anterior_Tibialis-SMR', 'other', 'stretching', 'intermediate', 'calves', ARRAY[]::text[]),
  ('Anti-Gravity_Press', 'barbell', 'strength', 'beginner', 'shoulders', ARRAY['middle back','traps','triceps']::text[]),
  ('Arm_Circles', NULL, 'stretching', 'beginner', 'shoulders', ARRAY['traps']::text[]),
  ('Arnold_Dumbbell_Press', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY['triceps']::text[]),
  ('Around_The_Worlds', 'dumbbell', 'strength', 'intermediate', 'chest', ARRAY['shoulders']::text[]),
  ('Atlas_Stone_Trainer', 'other', 'strongman', 'intermediate', 'lower back', ARRAY['biceps','forearms','glutes','hamstrings','quadriceps']::text[]),
  ('Atlas_Stones', 'other', 'strongman', 'expert', 'lower back', ARRAY['abdominals','adductors','biceps','calves','forearms','glutes','hamstrings','middle back','quadriceps','traps']::text[]),
  ('Axle_Deadlift', 'other', 'strongman', 'intermediate', 'lower back', ARRAY['forearms','glutes','hamstrings','middle back','quadriceps','traps']::text[]),
  ('Back_Flyes_-_With_Bands', 'bands', 'strength', 'beginner', 'shoulders', ARRAY['middle back','triceps']::text[]),
  ('Backward_Drag', 'other', 'strongman', 'beginner', 'quadriceps', ARRAY['calves','forearms','glutes','hamstrings','lower back']::text[]),
  ('Backward_Medicine_Ball_Throw', 'medicine ball', 'plyometrics', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Ball_Leg_Curl', 'exercise ball', 'strength', 'beginner', 'hamstrings', ARRAY['calves','glutes']::text[]),
  ('Band_Good_Morning', 'bands', 'powerlifting', 'beginner', 'hamstrings', ARRAY['glutes','lower back']::text[]),
  ('Band_Good_Morning_Pull_Through', 'bands', 'powerlifting', 'beginner', 'hamstrings', ARRAY['glutes','lower back']::text[]),
  ('Band_Hip_Adductions', 'bands', 'strength', 'beginner', 'adductors', ARRAY[]::text[]),
  ('Band_Pull_Apart', 'bands', 'strength', 'beginner', 'shoulders', ARRAY['middle back','traps']::text[]),
  ('Band_Skull_Crusher', 'bands', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Barbell_Ab_Rollout', 'barbell', 'strength', 'intermediate', 'abdominals', ARRAY['lower back','shoulders']::text[]),
  ('Barbell_Ab_Rollout_-_On_Knees', 'barbell', 'strength', 'expert', 'abdominals', ARRAY['lower back','shoulders']::text[]),
  ('Barbell_Bench_Press_-_Medium_Grip', 'barbell', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Barbell_Curls_Lying_Against_An_Incline', 'barbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Barbell_Hip_Thrust', 'barbell', 'powerlifting', 'intermediate', 'glutes', ARRAY['calves','hamstrings']::text[]),
  ('Barbell_Incline_Bench_Press_-_Medium_Grip', 'barbell', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Barbell_Rollout_from_Bench', 'barbell', 'strength', 'intermediate', 'abdominals', ARRAY['glutes','hamstrings','lats','shoulders']::text[]),
  ('Barbell_Shoulder_Press', 'barbell', 'strength', 'intermediate', 'shoulders', ARRAY['chest','triceps']::text[]),
  ('Barbell_Shrug_Behind_The_Back', 'barbell', 'strength', 'beginner', 'traps', ARRAY['forearms','middle back']::text[]),
  ('Barbell_Side_Bend', 'barbell', 'strength', 'beginner', 'abdominals', ARRAY['lower back']::text[]),
  ('Barbell_Squat', 'barbell', 'strength', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings','lower back']::text[]),
  ('Barbell_Squat_To_A_Bench', 'barbell', 'strength', 'expert', 'quadriceps', ARRAY['calves','glutes','hamstrings','lower back']::text[]),
  ('Barbell_Step_Ups', 'barbell', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings','quadriceps']::text[]),
  ('Barbell_Walking_Lunge', 'barbell', 'strength', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Bear_Crawl_Sled_Drags', 'other', 'strongman', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Bench_Dips', 'body only', 'strength', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Bench_Jump', 'body only', 'plyometrics', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Bench_Press_-_Powerlifting', 'barbell', 'powerlifting', 'intermediate', 'triceps', ARRAY['chest','forearms','lats','shoulders']::text[]),
  ('Bench_Press_-_With_Bands', 'bands', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Bench_Press_with_Chains', 'barbell', 'powerlifting', 'expert', 'triceps', ARRAY['chest','lats','shoulders']::text[]),
  ('Bench_Sprint', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Bent_Over_Barbell_Row', 'barbell', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats','shoulders']::text[]),
  ('Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Bent_Over_Low-Pulley_Side_Lateral', 'cable', 'strength', 'beginner', 'shoulders', ARRAY['lower back','middle back','traps']::text[]),
  ('Bent_Over_One-Arm_Long_Bar_Row', 'barbell', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats','lower back','traps']::text[]),
  ('Bent_Over_Two-Arm_Long_Bar_Row', 'barbell', 'strength', 'intermediate', 'middle back', ARRAY['biceps','lats']::text[]),
  ('Bent_Over_Two-Dumbbell_Row', 'dumbbell', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats','shoulders']::text[]),
  ('Bent_Over_Two-Dumbbell_Row_With_Palms_In', 'dumbbell', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats']::text[]),
  ('Bent_Press', 'kettlebells', 'strength', 'expert', 'abdominals', ARRAY['glutes','hamstrings','lower back','quadriceps','shoulders','triceps']::text[]),
  ('Bent-Arm_Barbell_Pullover', 'barbell', 'strength', 'intermediate', 'lats', ARRAY['chest','lats','shoulders','triceps']::text[]),
  ('Bent-Arm_Dumbbell_Pullover', 'dumbbell', 'strength', 'intermediate', 'chest', ARRAY['lats','shoulders','triceps']::text[]),
  ('Bent-Knee_Hip_Raise', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Bicycling', 'other', 'cardio', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Bicycling_Stationary', 'machine', 'cardio', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Board_Press', 'barbell', 'powerlifting', 'intermediate', 'triceps', ARRAY['chest','forearms','lats','shoulders']::text[]),
  ('Body_Tricep_Press', 'body only', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Bodyweight_Flyes', 'e-z curl bar', 'strength', 'intermediate', 'chest', ARRAY['abdominals','shoulders','triceps']::text[]),
  ('Bodyweight_Mid_Row', 'other', 'strength', 'intermediate', 'middle back', ARRAY['biceps','lats']::text[]),
  ('Bodyweight_Squat', 'body only', 'strength', 'beginner', 'quadriceps', ARRAY['glutes','hamstrings']::text[]),
  ('Bodyweight_Walking_Lunge', NULL, 'strength', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Bosu_Ball_Cable_Crunch_With_Side_Bends', 'cable', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Bottoms_Up', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Bottoms-Up_Clean_From_The_Hang_Position', 'kettlebells', 'strength', 'intermediate', 'forearms', ARRAY['biceps','shoulders']::text[]),
  ('Box_Jump_Multiple_Response', 'other', 'plyometrics', 'beginner', 'hamstrings', ARRAY['abductors','adductors','calves','glutes','quadriceps']::text[]),
  ('Box_Skip', 'other', 'plyometrics', 'beginner', 'hamstrings', ARRAY['abductors','adductors','calves','glutes','quadriceps']::text[]),
  ('Box_Squat', 'barbell', 'powerlifting', 'intermediate', 'quadriceps', ARRAY['adductors','calves','glutes','hamstrings','lower back']::text[]),
  ('Box_Squat_with_Bands', 'barbell', 'powerlifting', 'expert', 'quadriceps', ARRAY['abductors','adductors','calves','glutes','hamstrings','lower back']::text[]),
  ('Box_Squat_with_Chains', 'barbell', 'strength', 'expert', 'quadriceps', ARRAY['abductors','adductors','calves','glutes','hamstrings','lower back']::text[]),
  ('Brachialis-SMR', 'foam roll', 'stretching', 'intermediate', 'biceps', ARRAY[]::text[]),
  ('Bradford_Rocky_Presses', 'barbell', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Butt_Lift_Bridge', 'body only', 'strength', 'beginner', 'glutes', ARRAY['hamstrings']::text[]),
  ('Butterfly', 'machine', 'strength', 'beginner', 'chest', ARRAY[]::text[]),
  ('Cable_Chest_Press', 'cable', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Cable_Crossover', 'cable', 'strength', 'beginner', 'chest', ARRAY['shoulders']::text[]),
  ('Cable_Crunch', 'cable', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Cable_Deadlifts', 'cable', 'strength', 'beginner', 'quadriceps', ARRAY['forearms','glutes','hamstrings','lower back']::text[]),
  ('Cable_Hammer_Curls_-_Rope_Attachment', 'cable', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Cable_Internal_Rotation', 'cable', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Cable_Iron_Cross', 'cable', 'strength', 'beginner', 'chest', ARRAY[]::text[]),
  ('Cable_Lying_Triceps_Extension', 'cable', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Cable_One_Arm_Tricep_Extension', 'cable', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Cable_Rear_Delt_Fly', 'cable', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Cable_Rope_Overhead_Triceps_Extension', 'cable', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Cable_Rope_Rear-Delt_Rows', 'cable', 'strength', 'beginner', 'shoulders', ARRAY['biceps','middle back']::text[]),
  ('Cable_Russian_Twists', 'cable', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Cable_Seated_Lateral_Raise', 'cable', 'strength', 'beginner', 'shoulders', ARRAY['middle back','traps']::text[]),
  ('Cable_Shrugs', 'cable', 'strength', 'beginner', 'traps', ARRAY[]::text[]),
  ('Calf_Press', 'machine', 'strength', 'beginner', 'calves', ARRAY[]::text[]),
  ('Calf_Press_On_The_Leg_Press_Machine', 'machine', 'strength', 'beginner', 'calves', ARRAY[]::text[]),
  ('Calf_Raise_On_A_Dumbbell', 'dumbbell', 'strength', 'intermediate', 'calves', ARRAY[]::text[]),
  ('Calf_Raises_-_With_Bands', 'bands', 'strength', 'beginner', 'calves', ARRAY[]::text[]),
  ('Calf_Stretch_Elbows_Against_Wall', NULL, 'stretching', 'beginner', 'calves', ARRAY[]::text[]),
  ('Calf_Stretch_Hands_Against_Wall', NULL, 'stretching', 'beginner', 'calves', ARRAY[]::text[]),
  ('Calf-Machine_Shoulder_Shrug', 'machine', 'strength', 'beginner', 'traps', ARRAY[]::text[]),
  ('Calves-SMR', 'foam roll', 'stretching', 'intermediate', 'calves', ARRAY[]::text[]),
  ('Car_Deadlift', 'other', 'strongman', 'intermediate', 'quadriceps', ARRAY['forearms','glutes','hamstrings','lower back','traps']::text[]),
  ('Car_Drivers', 'barbell', 'strength', 'beginner', 'shoulders', ARRAY['forearms']::text[]),
  ('Carioca_Quick_Step', NULL, 'plyometrics', 'beginner', 'adductors', ARRAY['abdominals','abductors','calves','glutes','hamstrings','quadriceps']::text[]),
  ('Cat_Stretch', NULL, 'stretching', 'beginner', 'lower back', ARRAY['middle back','traps']::text[]),
  ('Catch_and_Overhead_Throw', 'medicine ball', 'plyometrics', 'beginner', 'lats', ARRAY['abdominals','chest','shoulders']::text[]),
  ('Chain_Handle_Extension', 'other', 'powerlifting', 'intermediate', 'triceps', ARRAY[]::text[]),
  ('Chain_Press', 'other', 'powerlifting', 'intermediate', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Chair_Lower_Back_Stretch', NULL, 'stretching', 'beginner', 'lats', ARRAY['lower back']::text[]),
  ('Chair_Squat', 'machine', 'strength', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Chair_Upper_Body_Stretch', 'other', 'stretching', 'beginner', 'shoulders', ARRAY['biceps','chest']::text[]),
  ('Chest_Push_from_3_point_stance', 'medicine ball', 'plyometrics', 'beginner', 'chest', ARRAY['abdominals','shoulders','triceps']::text[]),
  ('Chest_Push_multiple_response', 'medicine ball', 'plyometrics', 'beginner', 'chest', ARRAY['abdominals','shoulders','triceps']::text[]),
  ('Chest_Push_single_response', 'medicine ball', 'plyometrics', 'beginner', 'chest', ARRAY['abdominals','shoulders','triceps']::text[]),
  ('Chest_Push_with_Run_Release', 'medicine ball', 'plyometrics', 'beginner', 'chest', ARRAY['abdominals','shoulders','triceps']::text[]),
  ('Chest_Stretch_on_Stability_Ball', 'exercise ball', 'stretching', 'beginner', 'chest', ARRAY[]::text[]),
  ('Childs_Pose', NULL, 'stretching', 'beginner', 'lower back', ARRAY['glutes','middle back']::text[]),
  ('Chin_To_Chest_Stretch', NULL, 'stretching', 'beginner', 'neck', ARRAY['traps']::text[]),
  ('Circus_Bell', 'other', 'strongman', 'expert', 'shoulders', ARRAY['forearms','glutes','hamstrings','lower back','traps','triceps']::text[]),
  ('Clean', 'barbell', 'olympic weightlifting', 'intermediate', 'hamstrings', ARRAY['calves','forearms','glutes','lower back','quadriceps','shoulders','traps']::text[]),
  ('Clean_and_Jerk', 'barbell', 'olympic weightlifting', 'expert', 'shoulders', ARRAY['abdominals','glutes','hamstrings','lower back','quadriceps','traps','triceps']::text[]),
  ('Clean_and_Press', 'barbell', 'strength', 'intermediate', 'shoulders', ARRAY['abdominals','calves','glutes','hamstrings','lower back','middle back','quadriceps','shoulders','traps','triceps']::text[]),
  ('Clean_Deadlift', 'barbell', 'olympic weightlifting', 'beginner', 'hamstrings', ARRAY['forearms','glutes','lower back','middle back','quadriceps','traps']::text[]),
  ('Clean_from_Blocks', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings','shoulders','traps']::text[]),
  ('Clean_Pull', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['forearms','glutes','hamstrings','lower back','traps']::text[]),
  ('Clean_Shrug', 'barbell', 'olympic weightlifting', 'beginner', 'traps', ARRAY['forearms','shoulders']::text[]),
  ('Close-Grip_Barbell_Bench_Press', 'barbell', 'strength', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Close-Grip_Dumbbell_Press', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Close-Grip_EZ_Bar_Curl', 'barbell', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Close-Grip_EZ-Bar_Curl_with_Band', 'e-z curl bar', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Close-Grip_EZ-Bar_Press', 'e-z curl bar', 'strength', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Close-Grip_Front_Lat_Pulldown', 'cable', 'strength', 'beginner', 'lats', ARRAY['biceps','middle back','shoulders']::text[]),
  ('Close-Grip_Push-Up_off_of_a_Dumbbell', 'body only', 'strength', 'intermediate', 'triceps', ARRAY['abdominals','chest','shoulders']::text[]),
  ('Close-Grip_Standing_Barbell_Curl', 'barbell', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Conans_Wheel', 'other', 'strongman', 'intermediate', 'quadriceps', ARRAY['abdominals','biceps','calves','forearms','lower back','shoulders','traps']::text[]),
  ('Concentration_Curls', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Cross_Body_Hammer_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Cross_Over_-_With_Bands', 'bands', 'strength', 'beginner', 'chest', ARRAY['biceps','shoulders']::text[]),
  ('Cross-Body_Crunch', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Crossover_Reverse_Lunge', NULL, 'stretching', 'intermediate', 'lower back', ARRAY['abdominals','abductors','glutes','hamstrings','quadriceps']::text[]),
  ('Crucifix', 'other', 'strongman', 'beginner', 'shoulders', ARRAY['forearms']::text[]),
  ('Crunch_-_Hands_Overhead', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Crunch_-_Legs_On_Exercise_Ball', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Crunches', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Cuban_Press', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY['traps']::text[]),
  ('Dancers_Stretch', NULL, 'stretching', 'beginner', 'lower back', ARRAY['abductors','glutes']::text[]),
  ('Deadlift_with_Bands', 'barbell', 'powerlifting', 'expert', 'lower back', ARRAY['forearms','glutes','hamstrings','middle back','quadriceps','traps']::text[]),
  ('Deadlift_with_Chains', 'barbell', 'powerlifting', 'expert', 'lower back', ARRAY['forearms','glutes','hamstrings','middle back','quadriceps','traps']::text[]),
  ('Decline_Barbell_Bench_Press', 'barbell', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Decline_Close-Grip_Bench_To_Skull_Crusher', 'barbell', 'strength', 'intermediate', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Decline_Dumbbell_Bench_Press', 'dumbbell', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Decline_Dumbbell_Flyes', 'dumbbell', 'strength', 'beginner', 'chest', ARRAY[]::text[]),
  ('Decline_Dumbbell_Triceps_Extension', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Decline_EZ_Bar_Triceps_Extension', 'barbell', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Decline_Oblique_Crunch', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Decline_Reverse_Crunch', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Decline_Smith_Press', 'machine', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Deficit_Deadlift', 'barbell', 'powerlifting', 'intermediate', 'lower back', ARRAY['forearms','glutes','hamstrings','middle back','quadriceps','traps']::text[]),
  ('Depth_Jump_Leap', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['abductors','adductors','calves','glutes','hamstrings']::text[]),
  ('Dip_Machine', 'machine', 'strength', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Dips_-_Chest_Version', 'other', 'strength', 'intermediate', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Dips_-_Triceps_Version', 'body only', 'strength', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Donkey_Calf_Raises', 'other', 'strength', 'intermediate', 'calves', ARRAY[]::text[]),
  ('Double_Kettlebell_Alternating_Hang_Clean', 'kettlebells', 'strength', 'intermediate', 'hamstrings', ARRAY['biceps','calves','forearms','glutes','lower back','quadriceps','traps']::text[]),
  ('Double_Kettlebell_Jerk', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['calves','quadriceps','triceps']::text[]),
  ('Double_Kettlebell_Push_Press', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['calves','quadriceps','triceps']::text[]),
  ('Double_Kettlebell_Snatch', 'kettlebells', 'strength', 'expert', 'shoulders', ARRAY['glutes','hamstrings','quadriceps']::text[]),
  ('Double_Kettlebell_Windmill', 'kettlebells', 'strength', 'intermediate', 'abdominals', ARRAY['glutes','hamstrings','shoulders','triceps']::text[]),
  ('Double_Leg_Butt_Kick', 'body only', 'plyometrics', 'beginner', 'quadriceps', ARRAY['abductors','adductors','calves','glutes','hamstrings']::text[]),
  ('Downward_Facing_Balance', 'exercise ball', 'strength', 'intermediate', 'glutes', ARRAY['abdominals','hamstrings']::text[]),
  ('Drag_Curl', 'barbell', 'strength', 'intermediate', 'biceps', ARRAY['forearms']::text[]),
  ('Drop_Push', 'other', 'plyometrics', 'intermediate', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Dumbbell_Alternate_Bicep_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Dumbbell_Bench_Press_with_Neutral_Grip', 'dumbbell', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Dumbbell_Bicep_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Dumbbell_Floor_Press', 'dumbbell', 'powerlifting', 'intermediate', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Dumbbell_Flyes', 'dumbbell', 'strength', 'beginner', 'chest', ARRAY[]::text[]),
  ('Dumbbell_Lunges', 'dumbbell', 'strength', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Dumbbell_Lying_One-Arm_Rear_Lateral_Raise', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY['middle back']::text[]),
  ('Dumbbell_One-Arm_Shoulder_Press', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY['triceps']::text[]),
  ('Dumbbell_One-Arm_Triceps_Extension', 'dumbbell', 'strength', 'intermediate', 'triceps', ARRAY[]::text[]),
  ('Dumbbell_One-Arm_Upright_Row', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY['biceps','traps']::text[]),
  ('Dumbbell_Scaption', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY['traps']::text[]),
  ('Dumbbell_Seated_Box_Jump', 'dumbbell', 'plyometrics', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Dumbbell_Seated_One-Leg_Calf_Raise', 'dumbbell', 'strength', 'beginner', 'calves', ARRAY[]::text[]),
  ('Dumbbell_Shoulder_Press', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY['triceps']::text[]),
  ('Dumbbell_Squat_To_A_Bench', 'dumbbell', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings','lower back']::text[]),
  ('Dumbbell_Step_Ups', 'dumbbell', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Dumbbell_Tricep_Extension_-Pronated_Grip', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Dynamic_Back_Stretch', NULL, 'stretching', 'beginner', 'lats', ARRAY[]::text[]),
  ('Dynamic_Chest_Stretch', NULL, 'stretching', 'beginner', 'chest', ARRAY['middle back']::text[]),
  ('Elbow_Circles', NULL, 'stretching', 'beginner', 'shoulders', ARRAY['traps']::text[]),
  ('Elbow_to_Knee', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Elbows_Back', NULL, 'stretching', 'beginner', 'chest', ARRAY['shoulders']::text[]),
  ('Elevated_Back_Lunge', 'barbell', 'strength', 'intermediate', 'quadriceps', ARRAY['glutes','hamstrings']::text[]),
  ('Elevated_Cable_Rows', 'cable', 'strength', 'intermediate', 'lats', ARRAY['middle back','traps']::text[]),
  ('Elliptical_Trainer', 'machine', 'cardio', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Exercise_Ball_Crunch', 'exercise ball', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Exercise_Ball_Pull-In', 'exercise ball', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Extended_Range_One-Arm_Kettlebell_Floor_Press', 'kettlebells', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('External_Rotation', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('External_Rotation_with_Band', 'bands', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('External_Rotation_with_Cable', 'cable', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('EZ-Bar_Curl', 'e-z curl bar', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('EZ-Bar_Skullcrusher', 'e-z curl bar', 'strength', 'beginner', 'triceps', ARRAY['forearms']::text[]),
  ('Face_Pull', 'cable', 'strength', 'intermediate', 'shoulders', ARRAY['middle back']::text[]),
  ('Farmers_Walk', 'other', 'strongman', 'intermediate', 'forearms', ARRAY['abdominals','glutes','hamstrings','lower back','quadriceps','traps']::text[]),
  ('Fast_Skipping', 'body only', 'plyometrics', 'beginner', 'quadriceps', ARRAY['abductors','adductors','calves','glutes','hamstrings']::text[]),
  ('Flat_Bench_Cable_Flyes', 'cable', 'strength', 'intermediate', 'chest', ARRAY[]::text[]),
  ('Flat_Bench_Leg_Pull-In', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Flat_Bench_Lying_Leg_Raise', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Flexor_Incline_Dumbbell_Curls', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Floor_Glute-Ham_Raise', NULL, 'strength', 'intermediate', 'hamstrings', ARRAY['calves','glutes']::text[]),
  ('Floor_Press', 'barbell', 'powerlifting', 'intermediate', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Floor_Press_with_Chains', 'barbell', 'powerlifting', 'intermediate', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Foot-SMR', 'other', 'stretching', 'intermediate', 'calves', ARRAY[]::text[]),
  ('Forward_Drag_with_Press', 'other', 'strongman', 'intermediate', 'chest', ARRAY['calves','glutes','hamstrings','quadriceps','shoulders','triceps']::text[]),
  ('Freehand_Jump_Squat', 'body only', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Frog_Hops', NULL, 'stretching', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Frog_Sit-Ups', 'body only', 'strength', 'intermediate', 'abdominals', ARRAY[]::text[]),
  ('Front_Barbell_Squat', 'barbell', 'strength', 'expert', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Front_Barbell_Squat_To_A_Bench', 'barbell', 'strength', 'expert', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Front_Box_Jump', 'other', 'plyometrics', 'beginner', 'hamstrings', ARRAY['abductors','adductors','calves','glutes','quadriceps']::text[]),
  ('Front_Cable_Raise', 'cable', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Front_Cone_Hops_or_hurdle_hops', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['abductors','adductors','calves','glutes','hamstrings']::text[]),
  ('Front_Dumbbell_Raise', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Front_Incline_Dumbbell_Raise', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Front_Leg_Raises', 'body only', 'stretching', 'beginner', 'hamstrings', ARRAY[]::text[]),
  ('Front_Plate_Raise', 'other', 'strength', 'intermediate', 'shoulders', ARRAY[]::text[]),
  ('Front_Raise_And_Pullover', 'barbell', 'strength', 'beginner', 'chest', ARRAY['lats','shoulders','triceps']::text[]),
  ('Front_Squat_Clean_Grip', 'barbell', 'strength', 'intermediate', 'quadriceps', ARRAY['abdominals','glutes','hamstrings']::text[]),
  ('Front_Squats_With_Two_Kettlebells', 'kettlebells', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes']::text[]),
  ('Front_Two-Dumbbell_Raise', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Full_Range-Of-Motion_Lat_Pulldown', 'cable', 'strength', 'intermediate', 'lats', ARRAY['biceps','middle back','shoulders']::text[]),
  ('Gironda_Sternum_Chins', 'other', 'strength', 'intermediate', 'lats', ARRAY['biceps','middle back']::text[]),
  ('Glute_Ham_Raise', 'machine', 'powerlifting', 'intermediate', 'hamstrings', ARRAY['calves','glutes']::text[]),
  ('Glute_Kickback', 'body only', 'strength', 'beginner', 'glutes', ARRAY['hamstrings']::text[]),
  ('Goblet_Squat', 'kettlebells', 'strength', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings','shoulders']::text[]),
  ('Good_Morning', 'barbell', 'powerlifting', 'intermediate', 'hamstrings', ARRAY['abdominals','glutes','lower back']::text[]),
  ('Good_Morning_off_Pins', 'barbell', 'powerlifting', 'intermediate', 'hamstrings', ARRAY['abdominals','glutes','lower back']::text[]),
  ('Gorilla_Chin_Crunch', 'body only', 'strength', 'intermediate', 'abdominals', ARRAY['biceps','lats']::text[]),
  ('Groin_and_Back_Stretch', NULL, 'stretching', 'intermediate', 'adductors', ARRAY[]::text[]),
  ('Groiners', 'body only', 'stretching', 'intermediate', 'adductors', ARRAY[]::text[]),
  ('Hack_Squat', 'machine', 'strength', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Hammer_Curls', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Hammer_Grip_Incline_DB_Bench_Press', 'dumbbell', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Hamstring-SMR', 'foam roll', 'stretching', 'beginner', 'hamstrings', ARRAY[]::text[]),
  ('Handstand_Push-Ups', 'body only', 'strength', 'expert', 'shoulders', ARRAY['triceps']::text[]),
  ('Hang_Clean', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['calves','forearms','glutes','hamstrings','lower back','shoulders','traps']::text[]),
  ('Hang_Clean_-_Below_the_Knees', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['calves','forearms','glutes','hamstrings','lower back','shoulders','traps']::text[]),
  ('Hang_Snatch', 'barbell', 'olympic weightlifting', 'expert', 'hamstrings', ARRAY['abdominals','calves','forearms','glutes','lower back','quadriceps','shoulders','traps']::text[]),
  ('Hang_Snatch_-_Below_Knees', 'barbell', 'olympic weightlifting', 'expert', 'hamstrings', ARRAY['abdominals','calves','forearms','glutes','lower back','quadriceps','shoulders','traps']::text[]),
  ('Hanging_Bar_Good_Morning', 'barbell', 'powerlifting', 'intermediate', 'hamstrings', ARRAY['abdominals','glutes','lower back']::text[]),
  ('Heaving_Snatch_Balance', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['abdominals','forearms','glutes','hamstrings','shoulders','triceps']::text[]),
  ('Heavy_Bag_Thrust', 'other', 'plyometrics', 'beginner', 'chest', ARRAY['abdominals','shoulders','triceps']::text[]),
  ('High_Cable_Curls', 'cable', 'strength', 'intermediate', 'biceps', ARRAY[]::text[]),
  ('Hip_Circles_prone', 'body only', 'stretching', 'beginner', 'abductors', ARRAY['adductors']::text[]),
  ('Hip_Extension_with_Bands', 'bands', 'strength', 'beginner', 'glutes', ARRAY['hamstrings']::text[]),
  ('Hip_Flexion_with_Band', 'bands', 'strength', 'beginner', 'quadriceps', ARRAY[]::text[]),
  ('Hip_Lift_with_Band', 'bands', 'powerlifting', 'beginner', 'glutes', ARRAY['calves','hamstrings']::text[]),
  ('Hug_A_Ball', 'exercise ball', 'stretching', 'beginner', 'lower back', ARRAY['calves','glutes']::text[]),
  ('Hug_Knees_To_Chest', NULL, 'stretching', 'beginner', 'lower back', ARRAY['glutes']::text[]),
  ('Hurdle_Hops', 'other', 'plyometrics', 'beginner', 'hamstrings', ARRAY['abductors','adductors','calves','glutes','hamstrings']::text[]),
  ('Hyperextensions_Back_Extensions', 'other', 'strength', 'beginner', 'lower back', ARRAY['glutes','hamstrings']::text[]),
  ('Hyperextensions_With_No_Hyperextension_Bench', 'body only', 'strength', 'intermediate', 'lower back', ARRAY['glutes','hamstrings']::text[]),
  ('Iliotibial_Tract-SMR', 'foam roll', 'stretching', 'intermediate', 'abductors', ARRAY[]::text[]),
  ('Incline_Barbell_Triceps_Extension', 'barbell', 'strength', 'intermediate', 'triceps', ARRAY['forearms']::text[]),
  ('Incline_Bench_Pull', 'barbell', 'strength', 'beginner', 'middle back', ARRAY['lats','shoulders']::text[]),
  ('Incline_Cable_Chest_Press', 'cable', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Incline_Cable_Flye', 'cable', 'strength', 'intermediate', 'chest', ARRAY['shoulders']::text[]),
  ('Incline_Dumbbell_Bench_With_Palms_Facing_In', 'dumbbell', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Incline_Dumbbell_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Incline_Dumbbell_Flyes', 'dumbbell', 'strength', 'beginner', 'chest', ARRAY['shoulders']::text[]),
  ('Incline_Dumbbell_Flyes_-_With_A_Twist', 'dumbbell', 'strength', 'beginner', 'chest', ARRAY['shoulders']::text[]),
  ('Incline_Dumbbell_Press', 'dumbbell', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Incline_Hammer_Curls', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Incline_Inner_Biceps_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Incline_Push-Up_Close-Grip', 'body only', 'strength', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Incline_Push-Up_Depth_Jump', 'other', 'plyometrics', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Incline_Push-Up_Medium', 'body only', 'strength', 'beginner', 'chest', ARRAY['abdominals','shoulders','triceps']::text[]),
  ('Incline_Push-Up_Reverse_Grip', 'body only', 'strength', 'beginner', 'chest', ARRAY['abdominals','shoulders','triceps']::text[]),
  ('Incline_Push-Up_Wide', 'body only', 'strength', 'beginner', 'chest', ARRAY['abdominals','shoulders','triceps']::text[]),
  ('Intermediate_Groin_Stretch', 'other', 'stretching', 'intermediate', 'hamstrings', ARRAY[]::text[]),
  ('Internal_Rotation_with_Band', 'bands', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Iron_Cross', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY['chest','glutes','hamstrings','lower back','quadriceps','traps']::text[]),
  ('Iron_Crosses_stretch', NULL, 'stretching', 'intermediate', 'quadriceps', ARRAY[]::text[]),
  ('Isometric_Chest_Squeezes', 'body only', 'plyometrics', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Isometric_Neck_Exercise_-_Front_And_Back', 'body only', 'strength', 'beginner', 'neck', ARRAY[]::text[]),
  ('Isometric_Neck_Exercise_-_Sides', 'body only', 'strength', 'beginner', 'neck', ARRAY[]::text[]),
  ('IT_Band_and_Glute_Stretch', 'other', 'stretching', 'intermediate', 'abductors', ARRAY[]::text[]),
  ('Jefferson_Squats', 'barbell', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings','lower back','traps']::text[]),
  ('Jerk_Balance', 'barbell', 'olympic weightlifting', 'intermediate', 'shoulders', ARRAY['glutes','hamstrings','quadriceps','triceps']::text[]),
  ('Jerk_Dip_Squat', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['abdominals','calves']::text[]),
  ('JM_Press', 'barbell', 'strength', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Jogging_Treadmill', 'machine', 'cardio', 'beginner', 'quadriceps', ARRAY['glutes','hamstrings']::text[]),
  ('Keg_Load', 'other', 'strongman', 'intermediate', 'lower back', ARRAY['abdominals','biceps','calves','forearms','glutes','hamstrings','middle back','quadriceps','shoulders','traps']::text[]),
  ('Kettlebell_Dead_Clean', 'kettlebells', 'strength', 'intermediate', 'hamstrings', ARRAY['calves','glutes','lower back','quadriceps','traps']::text[]),
  ('Kettlebell_One-Legged_Deadlift', 'kettlebells', 'strength', 'intermediate', 'hamstrings', ARRAY['glutes','lower back']::text[]),
  ('Kettlebell_Pass_Between_The_Legs', 'kettlebells', 'strength', 'intermediate', 'abdominals', ARRAY['glutes','hamstrings','shoulders']::text[]),
  ('Kettlebell_Pirate_Ships', 'kettlebells', 'strength', 'beginner', 'shoulders', ARRAY['abdominals']::text[]),
  ('Kettlebell_Turkish_Get-Up_Lunge_style', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['abdominals','hamstrings','quadriceps','triceps']::text[]),
  ('Kettlebell_Turkish_Get-Up_Squat_style', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['abdominals','calves','hamstrings','quadriceps','triceps']::text[]),
  ('Knee_Across_The_Body', NULL, 'stretching', 'beginner', 'glutes', ARRAY['abductors','lower back']::text[]),
  ('Knee_Circles', 'body only', 'stretching', 'beginner', 'calves', ARRAY['hamstrings','quadriceps']::text[]),
  ('Knee_Hip_Raise_On_Parallel_Bars', 'other', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Knee_Tuck_Jump', 'body only', 'plyometrics', 'beginner', 'hamstrings', ARRAY['abductors','adductors','calves','glutes','quadriceps']::text[]),
  ('Kneeling_Arm_Drill', NULL, 'plyometrics', 'beginner', 'shoulders', ARRAY['abdominals']::text[]),
  ('Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists', 'cable', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Kneeling_Cable_Triceps_Extension', 'cable', 'strength', 'intermediate', 'triceps', ARRAY[]::text[]),
  ('Kneeling_Forearm_Stretch', NULL, 'stretching', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Kneeling_High_Pulley_Row', 'cable', 'strength', 'beginner', 'lats', ARRAY['biceps','middle back']::text[]),
  ('Kneeling_Hip_Flexor', NULL, 'stretching', 'beginner', 'quadriceps', ARRAY['quadriceps']::text[]),
  ('Kneeling_Single-Arm_High_Pulley_Row', 'cable', 'strength', 'beginner', 'lats', ARRAY['biceps','middle back']::text[]),
  ('Kneeling_Squat', 'barbell', 'powerlifting', 'intermediate', 'glutes', ARRAY['abdominals','hamstrings','lower back']::text[]),
  ('Landmine_180s', 'barbell', 'strength', 'beginner', 'abdominals', ARRAY['glutes','lower back','shoulders']::text[]),
  ('Landmine_Linear_Jammer', 'barbell', 'strength', 'intermediate', 'shoulders', ARRAY['abdominals','calves','chest','hamstrings','quadriceps','triceps']::text[]),
  ('Lateral_Bound', 'body only', 'plyometrics', 'beginner', 'adductors', ARRAY['abductors','calves','glutes','hamstrings','quadriceps']::text[]),
  ('Lateral_Box_Jump', 'other', 'plyometrics', 'beginner', 'adductors', ARRAY['abductors','calves','glutes','hamstrings','quadriceps']::text[]),
  ('Lateral_Cone_Hops', 'other', 'plyometrics', 'beginner', 'adductors', ARRAY['abductors','calves','glutes','hamstrings','quadriceps']::text[]),
  ('Lateral_Raise_-_With_Bands', 'bands', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Latissimus_Dorsi-SMR', 'foam roll', 'stretching', 'beginner', 'lats', ARRAY[]::text[]),
  ('Leg_Extensions', 'machine', 'strength', 'beginner', 'quadriceps', ARRAY[]::text[]),
  ('Leg_Lift', 'body only', 'strength', 'beginner', 'glutes', ARRAY['hamstrings']::text[]),
  ('Leg_Press', 'machine', 'strength', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Leg_Pull-In', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Leg-Over_Floor_Press', 'kettlebells', 'strength', 'intermediate', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Leg-Up_Hamstring_Stretch', NULL, 'stretching', 'beginner', 'hamstrings', ARRAY[]::text[]),
  ('Leverage_Chest_Press', 'machine', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Leverage_Deadlift', 'machine', 'strength', 'beginner', 'quadriceps', ARRAY['glutes','hamstrings']::text[]),
  ('Leverage_Decline_Chest_Press', 'machine', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Leverage_High_Row', 'machine', 'strength', 'beginner', 'middle back', ARRAY['lats']::text[]),
  ('Leverage_Incline_Chest_Press', 'machine', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Leverage_Iso_Row', 'machine', 'strength', 'beginner', 'lats', ARRAY['biceps','middle back']::text[]),
  ('Leverage_Shoulder_Press', 'machine', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Leverage_Shrug', 'machine', 'strength', 'beginner', 'traps', ARRAY['forearms']::text[]),
  ('Linear_3-Part_Start_Technique', NULL, 'plyometrics', 'beginner', 'hamstrings', ARRAY['calves','quadriceps']::text[]),
  ('Linear_Acceleration_Wall_Drill', NULL, 'plyometrics', 'beginner', 'hamstrings', ARRAY['calves','glutes','quadriceps']::text[]),
  ('Linear_Depth_Jump', 'other', 'plyometrics', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Log_Lift', 'other', 'strongman', 'intermediate', 'shoulders', ARRAY['abdominals','chest','glutes','hamstrings','lower back','middle back','quadriceps','traps','triceps']::text[]),
  ('London_Bridges', 'other', 'strength', 'intermediate', 'lats', ARRAY['biceps','forearms','middle back']::text[]),
  ('Looking_At_Ceiling', NULL, 'stretching', 'beginner', 'quadriceps', ARRAY[]::text[]),
  ('Low_Cable_Crossover', 'cable', 'strength', 'beginner', 'chest', ARRAY['shoulders']::text[]),
  ('Low_Cable_Triceps_Extension', 'cable', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Low_Pulley_Row_To_Neck', 'cable', 'strength', 'beginner', 'shoulders', ARRAY['biceps','middle back','traps']::text[]),
  ('Lower_Back-SMR', 'foam roll', 'stretching', 'beginner', 'lower back', ARRAY[]::text[]),
  ('Lunge_Pass_Through', 'kettlebells', 'strength', 'intermediate', 'hamstrings', ARRAY['calves','glutes','quadriceps']::text[]),
  ('Lunge_Sprint', 'machine', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Lying_Bent_Leg_Groin', 'other', 'stretching', 'expert', 'adductors', ARRAY[]::text[]),
  ('Lying_Cable_Curl', 'cable', 'strength', 'intermediate', 'biceps', ARRAY[]::text[]),
  ('Lying_Cambered_Barbell_Row', 'barbell', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats','traps']::text[]),
  ('Lying_Close-Grip_Bar_Curl_On_High_Pulley', 'cable', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head', 'barbell', 'strength', 'intermediate', 'triceps', ARRAY[]::text[]),
  ('Lying_Close-Grip_Barbell_Triceps_Press_To_Chin', 'e-z curl bar', 'strength', 'intermediate', 'triceps', ARRAY[]::text[]),
  ('Lying_Crossover', 'body only', 'stretching', 'expert', 'abductors', ARRAY[]::text[]),
  ('Lying_Dumbbell_Tricep_Extension', 'dumbbell', 'strength', 'intermediate', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Lying_Face_Down_Plate_Neck_Resistance', 'other', 'strength', 'intermediate', 'neck', ARRAY[]::text[]),
  ('Lying_Face_Up_Plate_Neck_Resistance', 'other', 'strength', 'intermediate', 'neck', ARRAY[]::text[]),
  ('Lying_Glute', 'body only', 'stretching', 'expert', 'glutes', ARRAY['abductors']::text[]),
  ('Lying_Hamstring', 'other', 'stretching', 'expert', 'hamstrings', ARRAY['calves']::text[]),
  ('Lying_High_Bench_Barbell_Curl', 'barbell', 'strength', 'intermediate', 'biceps', ARRAY[]::text[]),
  ('Lying_Leg_Curls', 'machine', 'strength', 'beginner', 'hamstrings', ARRAY[]::text[]),
  ('Lying_Machine_Squat', 'machine', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Lying_One-Arm_Lateral_Raise', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY[]::text[]),
  ('Lying_Prone_Quadriceps', 'body only', 'stretching', 'expert', 'quadriceps', ARRAY[]::text[]),
  ('Lying_Rear_Delt_Raise', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY[]::text[]),
  ('Lying_Supine_Dumbbell_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Lying_T-Bar_Row', 'machine', 'strength', 'intermediate', 'middle back', ARRAY['biceps','lats']::text[]),
  ('Lying_Triceps_Press', 'e-z curl bar', 'strength', 'intermediate', 'triceps', ARRAY[]::text[]),
  ('Machine_Bench_Press', 'machine', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Machine_Bicep_Curl', 'machine', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Machine_Preacher_Curls', 'machine', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Machine_Shoulder_Military_Press', 'machine', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Machine_Triceps_Extension', 'machine', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Medicine_Ball_Full_Twist', 'medicine ball', 'plyometrics', 'beginner', 'abdominals', ARRAY['shoulders']::text[]),
  ('Medicine_Ball_Scoop_Throw', 'medicine ball', 'plyometrics', 'beginner', 'shoulders', ARRAY['abdominals','hamstrings','quadriceps']::text[]),
  ('Middle_Back_Shrug', 'dumbbell', 'strength', 'intermediate', 'middle back', ARRAY[]::text[]),
  ('Middle_Back_Stretch', NULL, 'stretching', 'beginner', 'middle back', ARRAY['abdominals','lats','lower back']::text[]),
  ('Mixed_Grip_Chin', 'other', 'strength', 'expert', 'middle back', ARRAY['biceps','lats']::text[]),
  ('Mountain_Climbers', NULL, 'plyometrics', 'beginner', 'quadriceps', ARRAY['chest','hamstrings','shoulders']::text[]),
  ('Moving_Claw_Series', NULL, 'plyometrics', 'beginner', 'hamstrings', ARRAY['calves','quadriceps']::text[]),
  ('Muscle_Snatch', 'barbell', 'olympic weightlifting', 'intermediate', 'hamstrings', ARRAY['glutes','lower back','quadriceps','shoulders','triceps']::text[]),
  ('Narrow_Stance_Hack_Squats', 'machine', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Narrow_Stance_Leg_Press', 'machine', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Narrow_Stance_Squats', 'barbell', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings','lower back']::text[]),
  ('Natural_Glute_Ham_Raise', 'body only', 'strength', 'intermediate', 'hamstrings', ARRAY['calves','glutes','lower back']::text[]),
  ('Neck_Press', 'barbell', 'strength', 'intermediate', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Neck-SMR', 'other', 'stretching', 'intermediate', 'neck', ARRAY[]::text[]),
  ('Oblique_Crunches', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Oblique_Crunches_-_On_The_Floor', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Olympic_Squat', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('On_Your_Side_Quad_Stretch', NULL, 'stretching', 'beginner', 'quadriceps', ARRAY[]::text[]),
  ('On-Your-Back_Quad_Stretch', 'other', 'stretching', 'beginner', 'quadriceps', ARRAY[]::text[]),
  ('One_Arm_Dumbbell_Bench_Press', 'dumbbell', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('One_Arm_Dumbbell_Preacher_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('One_Arm_Floor_Press', 'barbell', 'strength', 'intermediate', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('One_Arm_Lat_Pulldown', 'cable', 'strength', 'beginner', 'lats', ARRAY['biceps','middle back']::text[]),
  ('One_Arm_Pronated_Dumbbell_Triceps_Extension', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('One_Arm_Supinated_Dumbbell_Triceps_Extension', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('One_Half_Locust', NULL, 'stretching', 'beginner', 'quadriceps', ARRAY['abdominals','biceps','chest']::text[]),
  ('One_Handed_Hang', 'other', 'stretching', 'beginner', 'lats', ARRAY['biceps']::text[]),
  ('One_Knee_To_Chest', NULL, 'stretching', 'beginner', 'glutes', ARRAY['hamstrings','lower back']::text[]),
  ('One_Leg_Barbell_Squat', 'barbell', 'strength', 'expert', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('One-Arm_Dumbbell_Row', 'dumbbell', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats','shoulders']::text[]),
  ('One-Arm_Flat_Bench_Dumbbell_Flye', 'dumbbell', 'strength', 'beginner', 'chest', ARRAY[]::text[]),
  ('One-Arm_High-Pulley_Cable_Side_Bends', 'cable', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('One-Arm_Incline_Lateral_Raise', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('One-Arm_Kettlebell_Clean', 'kettlebells', 'strength', 'intermediate', 'hamstrings', ARRAY['glutes','lower back','shoulders','traps']::text[]),
  ('One-Arm_Kettlebell_Clean_and_Jerk', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY[]::text[]),
  ('One-Arm_Kettlebell_Floor_Press', 'kettlebells', 'strength', 'intermediate', 'chest', ARRAY['triceps']::text[]),
  ('One-Arm_Kettlebell_Jerk', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['calves','quadriceps','triceps']::text[]),
  ('One-Arm_Kettlebell_Military_Press_To_The_Side', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['triceps']::text[]),
  ('One-Arm_Kettlebell_Para_Press', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['triceps']::text[]),
  ('One-Arm_Kettlebell_Push_Press', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['calves','quadriceps','triceps']::text[]),
  ('One-Arm_Kettlebell_Row', 'kettlebells', 'strength', 'intermediate', 'middle back', ARRAY['biceps','lats']::text[]),
  ('One-Arm_Kettlebell_Snatch', 'kettlebells', 'strength', 'expert', 'shoulders', ARRAY['calves','glutes','hamstrings','lower back','traps','triceps']::text[]),
  ('One-Arm_Kettlebell_Split_Jerk', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['glutes','hamstrings','quadriceps','triceps']::text[]),
  ('One-Arm_Kettlebell_Split_Snatch', 'kettlebells', 'strength', 'expert', 'shoulders', ARRAY['hamstrings','quadriceps']::text[]),
  ('One-Arm_Kettlebell_Swings', 'kettlebells', 'strength', 'intermediate', 'hamstrings', ARRAY['calves','glutes','lower back','shoulders']::text[]),
  ('One-Arm_Long_Bar_Row', 'barbell', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats']::text[]),
  ('One-Arm_Medicine_Ball_Slam', 'medicine ball', 'strength', 'beginner', 'abdominals', ARRAY['lats','shoulders']::text[]),
  ('One-Arm_Open_Palm_Kettlebell_Clean', 'kettlebells', 'strength', 'intermediate', 'hamstrings', ARRAY['forearms','glutes','lower back','quadriceps','shoulders']::text[]),
  ('One-Arm_Overhead_Kettlebell_Squats', 'kettlebells', 'strength', 'expert', 'quadriceps', ARRAY['calves','glutes','hamstrings','shoulders']::text[]),
  ('One-Arm_Side_Deadlift', 'barbell', 'strength', 'expert', 'quadriceps', ARRAY['abdominals','calves','glutes','hamstrings','lower back','traps']::text[]),
  ('One-Arm_Side_Laterals', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('One-Legged_Cable_Kickback', 'cable', 'strength', 'intermediate', 'glutes', ARRAY['hamstrings']::text[]),
  ('Open_Palm_Kettlebell_Clean', 'kettlebells', 'strength', 'expert', 'hamstrings', ARRAY['glutes','lower back','quadriceps','shoulders']::text[]),
  ('Otis-Up', 'other', 'strength', 'beginner', 'abdominals', ARRAY['chest','shoulders','triceps']::text[]),
  ('Overhead_Cable_Curl', 'cable', 'strength', 'intermediate', 'biceps', ARRAY[]::text[]),
  ('Overhead_Lat', 'other', 'stretching', 'expert', 'lats', ARRAY['triceps']::text[]),
  ('Overhead_Slam', 'medicine ball', 'plyometrics', 'beginner', 'lats', ARRAY[]::text[]),
  ('Overhead_Squat', 'barbell', 'olympic weightlifting', 'expert', 'quadriceps', ARRAY['abdominals','calves','glutes','hamstrings','lower back','shoulders','triceps']::text[]),
  ('Overhead_Stretch', NULL, 'stretching', 'beginner', 'abdominals', ARRAY['chest','forearms','lats','triceps']::text[]),
  ('Overhead_Triceps', 'body only', 'stretching', 'expert', 'triceps', ARRAY['lats']::text[]),
  ('Pallof_Press', 'cable', 'strength', 'beginner', 'abdominals', ARRAY['chest','shoulders','triceps']::text[]),
  ('Pallof_Press_With_Rotation', 'cable', 'strength', 'beginner', 'abdominals', ARRAY['chest','shoulders','triceps']::text[]),
  ('Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench', 'dumbbell', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Palms-Down_Wrist_Curl_Over_A_Bench', 'barbell', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Palms-Up_Barbell_Wrist_Curl_Over_A_Bench', 'barbell', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench', 'dumbbell', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Parallel_Bar_Dip', 'other', 'strength', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Peroneals-SMR', 'foam roll', 'stretching', 'intermediate', 'calves', ARRAY[]::text[]),
  ('Physioball_Hip_Bridge', 'exercise ball', 'strength', 'beginner', 'glutes', ARRAY['hamstrings']::text[]),
  ('Pin_Presses', 'barbell', 'powerlifting', 'intermediate', 'triceps', ARRAY['chest','forearms','lats','middle back','shoulders']::text[]),
  ('Piriformis-SMR', 'foam roll', 'stretching', 'intermediate', 'glutes', ARRAY[]::text[]),
  ('Plank', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Plate_Pinch', 'other', 'strength', 'intermediate', 'forearms', ARRAY[]::text[]),
  ('Plate_Twist', 'other', 'strength', 'intermediate', 'abdominals', ARRAY[]::text[]),
  ('Platform_Hamstring_Slides', 'other', 'strength', 'beginner', 'hamstrings', ARRAY['glutes']::text[]),
  ('Plie_Dumbbell_Squat', 'dumbbell', 'strength', 'beginner', 'quadriceps', ARRAY['abdominals','calves','glutes','hamstrings']::text[]),
  ('Plyo_Kettlebell_Pushups', 'kettlebells', 'strength', 'expert', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Plyo_Push-up', 'body only', 'plyometrics', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Power_Clean_from_Blocks', 'barbell', 'olympic weightlifting', 'intermediate', 'hamstrings', ARRAY['quadriceps']::text[]),
  ('Power_Jerk', 'barbell', 'olympic weightlifting', 'expert', 'quadriceps', ARRAY['abdominals','calves','glutes','hamstrings','shoulders','triceps']::text[]),
  ('Power_Partials', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Power_Snatch', 'barbell', 'olympic weightlifting', 'expert', 'hamstrings', ARRAY['calves','glutes','lower back','quadriceps','shoulders','traps','triceps']::text[]),
  ('Power_Snatch_from_Blocks', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['calves','forearms','glutes','hamstrings','lower back','shoulders','traps','triceps']::text[]),
  ('Power_Stairs', 'other', 'strongman', 'intermediate', 'hamstrings', ARRAY['adductors','calves','glutes','lower back','quadriceps','shoulders','traps']::text[]),
  ('Preacher_Curl', 'barbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Preacher_Hammer_Dumbbell_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Press_Sit-Up', 'barbell', 'strength', 'expert', 'abdominals', ARRAY['chest','shoulders','triceps']::text[]),
  ('Prone_Manual_Hamstring', NULL, 'strength', 'beginner', 'hamstrings', ARRAY[]::text[]),
  ('Prowler_Sprint', 'other', 'cardio', 'beginner', 'hamstrings', ARRAY['calves','chest','glutes','quadriceps','shoulders']::text[]),
  ('Pull_Through', 'cable', 'strength', 'beginner', 'glutes', ARRAY['hamstrings','lower back']::text[]),
  ('Pullups', 'body only', 'strength', 'beginner', 'lats', ARRAY['biceps','middle back']::text[]),
  ('Push_Press', 'barbell', 'olympic weightlifting', 'expert', 'shoulders', ARRAY['quadriceps','triceps']::text[]),
  ('Push_Press_-_Behind_the_Neck', 'barbell', 'olympic weightlifting', 'intermediate', 'shoulders', ARRAY['calves','quadriceps','triceps']::text[]),
  ('Push-Up_Wide', 'body only', 'strength', 'beginner', 'chest', ARRAY['abdominals','shoulders','triceps']::text[]),
  ('Push-Ups_-_Close_Triceps_Position', 'body only', 'strength', 'intermediate', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Push-Ups_With_Feet_Elevated', 'body only', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Push-Ups_With_Feet_On_An_Exercise_Ball', 'exercise ball', 'strength', 'intermediate', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Pushups', 'body only', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Pushups_Close_and_Wide_Hand_Positions', 'body only', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Pyramid', 'exercise ball', 'stretching', 'beginner', 'lower back', ARRAY['shoulders']::text[]),
  ('Quad_Stretch', 'other', 'stretching', 'intermediate', 'quadriceps', ARRAY[]::text[]),
  ('Quadriceps-SMR', 'foam roll', 'stretching', 'intermediate', 'quadriceps', ARRAY[]::text[]),
  ('Quick_Leap', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['calves','hamstrings']::text[]),
  ('Rack_Delivery', 'barbell', 'olympic weightlifting', 'intermediate', 'shoulders', ARRAY['forearms','traps']::text[]),
  ('Rack_Pull_with_Bands', 'barbell', 'powerlifting', 'intermediate', 'lower back', ARRAY['forearms','glutes','hamstrings','quadriceps','traps']::text[]),
  ('Rack_Pulls', 'barbell', 'powerlifting', 'intermediate', 'lower back', ARRAY['forearms','glutes','hamstrings','traps']::text[]),
  ('Rear_Leg_Raises', 'body only', 'stretching', 'beginner', 'quadriceps', ARRAY[]::text[]),
  ('Recumbent_Bike', 'machine', 'cardio', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Return_Push_from_Stance', 'medicine ball', 'plyometrics', 'beginner', 'shoulders', ARRAY['chest','triceps']::text[]),
  ('Reverse_Band_Bench_Press', 'barbell', 'powerlifting', 'intermediate', 'triceps', ARRAY['chest','forearms','lats','middle back','shoulders']::text[]),
  ('Reverse_Band_Box_Squat', 'barbell', 'powerlifting', 'intermediate', 'quadriceps', ARRAY['abductors','adductors','calves','forearms','glutes','hamstrings','lower back']::text[]),
  ('Reverse_Band_Deadlift', 'barbell', 'powerlifting', 'expert', 'lower back', ARRAY['abductors','adductors','calves','glutes','hamstrings','quadriceps']::text[]),
  ('Reverse_Band_Power_Squat', 'barbell', 'powerlifting', 'expert', 'quadriceps', ARRAY['adductors','calves','glutes','hamstrings','lower back']::text[]),
  ('Reverse_Band_Sumo_Deadlift', 'barbell', 'powerlifting', 'expert', 'hamstrings', ARRAY['abductors','adductors','calves','forearms','glutes','lower back','quadriceps','traps']::text[]),
  ('Reverse_Barbell_Curl', 'barbell', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Reverse_Barbell_Preacher_Curls', 'e-z curl bar', 'strength', 'intermediate', 'biceps', ARRAY['forearms']::text[]),
  ('Reverse_Cable_Curl', 'cable', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Reverse_Flyes', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Reverse_Flyes_With_External_Rotation', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY[]::text[]),
  ('Reverse_Grip_Bent-Over_Rows', 'barbell', 'strength', 'intermediate', 'middle back', ARRAY['biceps','lats','shoulders']::text[]),
  ('Reverse_Grip_Triceps_Pushdown', 'cable', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Reverse_Hyperextension', 'machine', 'strength', 'intermediate', 'hamstrings', ARRAY['calves','glutes']::text[]),
  ('Reverse_Machine_Flyes', 'machine', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Reverse_Plate_Curls', 'other', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Reverse_Triceps_Bench_Press', 'barbell', 'strength', 'intermediate', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Rhomboids-SMR', 'foam roll', 'stretching', 'intermediate', 'middle back', ARRAY['traps']::text[]),
  ('Rickshaw_Carry', 'other', 'strongman', 'intermediate', 'forearms', ARRAY['abdominals','calves','glutes','hamstrings','lower back','quadriceps','traps']::text[]),
  ('Rickshaw_Deadlift', 'other', 'strongman', 'intermediate', 'quadriceps', ARRAY['forearms','glutes','hamstrings','lower back','traps']::text[]),
  ('Rocket_Jump', 'body only', 'plyometrics', 'beginner', 'quadriceps', ARRAY['calves','hamstrings']::text[]),
  ('Rocking_Standing_Calf_Raise', 'barbell', 'strength', 'beginner', 'calves', ARRAY[]::text[]),
  ('Rocky_Pull-Ups_Pulldowns', 'other', 'strength', 'intermediate', 'lats', ARRAY['biceps','middle back','shoulders']::text[]),
  ('Romanian_Deadlift', 'barbell', 'strength', 'intermediate', 'hamstrings', ARRAY['calves','glutes','lower back']::text[]),
  ('Romanian_Deadlift_from_Deficit', 'barbell', 'olympic weightlifting', 'intermediate', 'hamstrings', ARRAY['forearms','glutes','lower back','traps']::text[]),
  ('Rope_Crunch', 'cable', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Rope_Jumping', 'other', 'cardio', 'intermediate', 'quadriceps', ARRAY['calves','hamstrings']::text[]),
  ('Rope_Straight-Arm_Pulldown', 'cable', 'strength', 'beginner', 'lats', ARRAY[]::text[]),
  ('Round_The_World_Shoulder_Stretch', 'other', 'stretching', 'beginner', 'shoulders', ARRAY['biceps','chest']::text[]),
  ('Rowing_Stationary', 'machine', 'cardio', 'intermediate', 'quadriceps', ARRAY['biceps','calves','glutes','hamstrings','lower back','middle back']::text[]),
  ('Runners_Stretch', NULL, 'stretching', 'beginner', 'hamstrings', ARRAY['calves']::text[]),
  ('Running_Treadmill', 'machine', 'cardio', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Sandbag_Load', 'other', 'strongman', 'beginner', 'quadriceps', ARRAY['abdominals','biceps','calves','forearms','glutes','hamstrings','lower back','middle back','shoulders','traps']::text[]),
  ('Scissor_Kick', 'body only', 'stretching', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Scissors_Jump', 'body only', 'plyometrics', 'beginner', 'quadriceps', ARRAY['glutes','hamstrings']::text[]),
  ('Seated_Band_Hamstring_Curl', 'other', 'strength', 'beginner', 'hamstrings', ARRAY[]::text[]),
  ('Seated_Barbell_Military_Press', 'barbell', 'strength', 'intermediate', 'shoulders', ARRAY['triceps']::text[]),
  ('Seated_Barbell_Twist', 'barbell', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Seated_Bent-Over_Rear_Delt_Raise', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY[]::text[]),
  ('Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension', 'dumbbell', 'strength', 'intermediate', 'triceps', ARRAY[]::text[]),
  ('Seated_Biceps', 'body only', 'stretching', 'expert', 'biceps', ARRAY['chest','shoulders']::text[]),
  ('Seated_Cable_Rows', 'cable', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats','shoulders']::text[]),
  ('Seated_Cable_Shoulder_Press', 'cable', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Seated_Calf_Raise', 'machine', 'strength', 'beginner', 'calves', ARRAY[]::text[]),
  ('Seated_Calf_Stretch', NULL, 'stretching', 'beginner', 'calves', ARRAY['hamstrings','lower back']::text[]),
  ('Seated_Close-Grip_Concentration_Barbell_Curl', 'barbell', 'strength', 'intermediate', 'biceps', ARRAY[]::text[]),
  ('Seated_Dumbbell_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Seated_Dumbbell_Inner_Biceps_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Seated_Dumbbell_Palms-Down_Wrist_Curl', 'dumbbell', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Seated_Dumbbell_Palms-Up_Wrist_Curl', 'dumbbell', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Seated_Dumbbell_Press', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Seated_Flat_Bench_Leg_Pull-In', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Seated_Floor_Hamstring_Stretch', NULL, 'stretching', 'beginner', 'hamstrings', ARRAY['calves']::text[]),
  ('Seated_Front_Deltoid', 'body only', 'stretching', 'expert', 'shoulders', ARRAY['chest']::text[]),
  ('Seated_Glute', 'body only', 'stretching', 'expert', 'glutes', ARRAY['adductors']::text[]),
  ('Seated_Good_Mornings', 'barbell', 'powerlifting', 'intermediate', 'lower back', ARRAY['glutes']::text[]),
  ('Seated_Hamstring', NULL, 'stretching', 'expert', 'hamstrings', ARRAY['calves']::text[]),
  ('Seated_Hamstring_and_Calf_Stretch', 'other', 'stretching', 'intermediate', 'hamstrings', ARRAY['calves']::text[]),
  ('Seated_Head_Harness_Neck_Resistance', 'other', 'strength', 'intermediate', 'neck', ARRAY[]::text[]),
  ('Seated_Leg_Curl', 'machine', 'strength', 'beginner', 'hamstrings', ARRAY[]::text[]),
  ('Seated_Leg_Tucks', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Seated_One-arm_Cable_Pulley_Rows', 'cable', 'strength', 'intermediate', 'middle back', ARRAY['biceps','lats','traps']::text[]),
  ('Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl', 'dumbbell', 'strength', 'intermediate', 'forearms', ARRAY[]::text[]),
  ('Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl', 'dumbbell', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Seated_Overhead_Stretch', NULL, 'stretching', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Seated_Palm-Up_Barbell_Wrist_Curl', 'barbell', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Seated_Palms-Down_Barbell_Wrist_Curl', 'barbell', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Seated_Side_Lateral_Raise', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Seated_Triceps_Press', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl', 'cable', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('See-Saw_Press_Alternating_Side_Press', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY['abdominals','triceps']::text[]),
  ('Shotgun_Row', 'cable', 'strength', 'beginner', 'lats', ARRAY['biceps','middle back']::text[]),
  ('Shoulder_Circles', NULL, 'stretching', 'beginner', 'shoulders', ARRAY['traps']::text[]),
  ('Shoulder_Press_-_With_Bands', 'bands', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Shoulder_Raise', NULL, 'stretching', 'beginner', 'shoulders', ARRAY['lats']::text[]),
  ('Shoulder_Stretch', NULL, 'stretching', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Side_Bridge', 'body only', 'strength', 'beginner', 'abdominals', ARRAY['shoulders']::text[]),
  ('Side_Hop-Sprint', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['abductors','adductors','calves','hamstrings']::text[]),
  ('Side_Jackknife', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Side_Lateral_Raise', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Side_Laterals_to_Front_Raise', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY['traps']::text[]),
  ('Side_Leg_Raises', 'body only', 'stretching', 'beginner', 'adductors', ARRAY[]::text[]),
  ('Side_Lying_Groin_Stretch', NULL, 'stretching', 'beginner', 'adductors', ARRAY['hamstrings']::text[]),
  ('Side_Neck_Stretch', NULL, 'stretching', 'beginner', 'neck', ARRAY[]::text[]),
  ('Side_Standing_Long_Jump', NULL, 'plyometrics', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Side_to_Side_Box_Shuffle', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['abductors','adductors','calves','hamstrings']::text[]),
  ('Side_To_Side_Chins', 'other', 'strength', 'intermediate', 'lats', ARRAY['biceps','forearms','middle back','shoulders']::text[]),
  ('Side_Wrist_Pull', NULL, 'stretching', 'beginner', 'shoulders', ARRAY['forearms','lats']::text[]),
  ('Side-Lying_Floor_Stretch', NULL, 'stretching', 'beginner', 'lats', ARRAY[]::text[]),
  ('Single_Dumbbell_Raise', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY['forearms','traps']::text[]),
  ('Single_Leg_Butt_Kick', 'body only', 'plyometrics', 'beginner', 'quadriceps', ARRAY['calves','hamstrings']::text[]),
  ('Single_Leg_Glute_Bridge', 'body only', 'strength', 'beginner', 'glutes', ARRAY['hamstrings']::text[]),
  ('Single_Leg_Push-off', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['calves','hamstrings']::text[]),
  ('Single-Arm_Cable_Crossover', 'cable', 'strength', 'beginner', 'chest', ARRAY[]::text[]),
  ('Single-Arm_Linear_Jammer', 'barbell', 'strength', 'intermediate', 'shoulders', ARRAY['chest','triceps']::text[]),
  ('Single-Arm_Push-Up', 'body only', 'strength', 'intermediate', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Single-Cone_Sprint_Drill', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Single-Leg_High_Box_Squat', 'other', 'strength', 'beginner', 'quadriceps', ARRAY['glutes','hamstrings']::text[]),
  ('Single-Leg_Hop_Progression', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['abductors','adductors','calves','hamstrings']::text[]),
  ('Single-Leg_Lateral_Hop', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['abductors','adductors','calves','hamstrings']::text[]),
  ('Single-Leg_Leg_Extension', 'machine', 'strength', 'beginner', 'quadriceps', ARRAY[]::text[]),
  ('Single-Leg_Stride_Jump', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['abductors','adductors','calves','hamstrings']::text[]),
  ('Sit_Squats', NULL, 'stretching', 'beginner', 'quadriceps', ARRAY['abductors','glutes','hamstrings']::text[]),
  ('Sit-Up', 'body only', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Skating', 'other', 'cardio', 'intermediate', 'quadriceps', ARRAY['abductors','adductors','calves','glutes','hamstrings']::text[]),
  ('Sled_Drag_-_Harness', 'other', 'strongman', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Sled_Overhead_Backward_Walk', 'other', 'strength', 'beginner', 'shoulders', ARRAY['calves','middle back','quadriceps']::text[]),
  ('Sled_Overhead_Triceps_Extension', 'other', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Sled_Push', 'other', 'strongman', 'beginner', 'quadriceps', ARRAY['calves','chest','glutes','hamstrings','triceps']::text[]),
  ('Sled_Reverse_Flye', 'other', 'strength', 'beginner', 'shoulders', ARRAY[]::text[]),
  ('Sled_Row', 'other', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats']::text[]),
  ('Sledgehammer_Swings', 'other', 'plyometrics', 'beginner', 'abdominals', ARRAY['calves','forearms','lats','middle back','shoulders']::text[]),
  ('Smith_Incline_Shoulder_Raise', 'barbell', 'strength', 'beginner', 'shoulders', ARRAY['chest']::text[]),
  ('Smith_Machine_Behind_the_Back_Shrug', 'machine', 'strength', 'beginner', 'traps', ARRAY['shoulders']::text[]),
  ('Smith_Machine_Bench_Press', 'machine', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Smith_Machine_Bent_Over_Row', 'machine', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats','shoulders']::text[]),
  ('Smith_Machine_Calf_Raise', 'machine', 'strength', 'beginner', 'calves', ARRAY[]::text[]),
  ('Smith_Machine_Close-Grip_Bench_Press', 'machine', 'strength', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Smith_Machine_Decline_Press', 'machine', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Smith_Machine_Hang_Power_Clean', 'machine', 'strength', 'intermediate', 'hamstrings', ARRAY['glutes','lower back','quadriceps','shoulders','traps']::text[]),
  ('Smith_Machine_Hip_Raise', 'machine', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Smith_Machine_Incline_Bench_Press', 'machine', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Smith_Machine_Leg_Press', 'machine', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Smith_Machine_One-Arm_Upright_Row', 'machine', 'strength', 'beginner', 'shoulders', ARRAY['biceps','traps']::text[]),
  ('Smith_Machine_Overhead_Shoulder_Press', 'machine', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Smith_Machine_Pistol_Squat', 'machine', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Smith_Machine_Reverse_Calf_Raises', 'machine', 'strength', 'beginner', 'calves', ARRAY[]::text[]),
  ('Smith_Machine_Squat', 'machine', 'strength', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings','lower back']::text[]),
  ('Smith_Machine_Stiff-Legged_Deadlift', 'machine', 'strength', 'beginner', 'hamstrings', ARRAY['glutes','lower back']::text[]),
  ('Smith_Machine_Upright_Row', 'machine', 'strength', 'beginner', 'traps', ARRAY['biceps','middle back','shoulders']::text[]),
  ('Smith_Single-Leg_Split_Squat', 'machine', 'strength', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Snatch', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['biceps','glutes','hamstrings','lower back','shoulders','traps','triceps']::text[]),
  ('Snatch_Balance', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings','shoulders','triceps']::text[]),
  ('Snatch_Deadlift', 'barbell', 'olympic weightlifting', 'intermediate', 'hamstrings', ARRAY['forearms','glutes','hamstrings','lower back','quadriceps','traps']::text[]),
  ('Snatch_from_Blocks', 'barbell', 'olympic weightlifting', 'expert', 'quadriceps', ARRAY['calves','forearms','glutes','hamstrings','lower back','shoulders','traps','triceps']::text[]),
  ('Snatch_Shrug', 'barbell', 'olympic weightlifting', 'intermediate', 'traps', ARRAY['forearms','shoulders']::text[]),
  ('Speed_Band_Overhead_Triceps', 'bands', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Speed_Box_Squat', 'barbell', 'powerlifting', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Speed_Squats', 'barbell', 'strength', 'expert', 'quadriceps', ARRAY['calves','glutes','hamstrings','lower back']::text[]),
  ('Spider_Crawl', 'body only', 'strength', 'beginner', 'abdominals', ARRAY['chest','shoulders','triceps']::text[]),
  ('Spider_Curl', 'e-z curl bar', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Spinal_Stretch', NULL, 'stretching', 'beginner', 'middle back', ARRAY['lats','lower back','neck','traps']::text[]),
  ('Split_Clean', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['calves','forearms','glutes','hamstrings','lower back','shoulders','traps']::text[]),
  ('Split_Jerk', 'barbell', 'olympic weightlifting', 'intermediate', 'quadriceps', ARRAY['glutes','hamstrings','shoulders','triceps']::text[]),
  ('Split_Jump', 'body only', 'plyometrics', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Split_Snatch', 'barbell', 'olympic weightlifting', 'expert', 'hamstrings', ARRAY['calves','forearms','glutes','hamstrings','lower back','quadriceps','shoulders','traps','triceps']::text[]),
  ('Split_Squat_with_Dumbbells', 'dumbbell', 'strength', 'beginner', 'quadriceps', ARRAY['glutes','hamstrings']::text[]),
  ('Squat_with_Bands', 'barbell', 'powerlifting', 'intermediate', 'quadriceps', ARRAY['adductors','calves','glutes','hamstrings','lower back']::text[]),
  ('Squat_with_Chains', 'barbell', 'powerlifting', 'intermediate', 'quadriceps', ARRAY['adductors','calves','glutes','hamstrings','lower back']::text[]),
  ('Squat_with_Plate_Movers', 'barbell', 'strength', 'intermediate', 'quadriceps', ARRAY['abductors','adductors','calves','glutes','hamstrings']::text[]),
  ('Squats_-_With_Bands', 'bands', 'strength', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings','lower back']::text[]),
  ('Stairmaster', 'machine', 'cardio', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Standing_Alternating_Dumbbell_Press', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Standing_Barbell_Calf_Raise', 'barbell', 'strength', 'beginner', 'calves', ARRAY[]::text[]),
  ('Standing_Barbell_Press_Behind_Neck', 'barbell', 'strength', 'intermediate', 'shoulders', ARRAY['triceps']::text[]),
  ('Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY['shoulders']::text[]),
  ('Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Standing_Biceps_Cable_Curl', 'cable', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Standing_Biceps_Stretch', 'other', 'stretching', 'beginner', 'biceps', ARRAY['chest','shoulders']::text[]),
  ('Standing_Bradford_Press', 'barbell', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Standing_Cable_Chest_Press', 'cable', 'strength', 'beginner', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Standing_Cable_Lift', 'cable', 'strength', 'beginner', 'abdominals', ARRAY['shoulders']::text[]),
  ('Standing_Cable_Wood_Chop', 'cable', 'strength', 'beginner', 'abdominals', ARRAY['shoulders']::text[]),
  ('Standing_Calf_Raises', 'machine', 'strength', 'beginner', 'calves', ARRAY[]::text[]),
  ('Standing_Concentration_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY['forearms']::text[]),
  ('Standing_Dumbbell_Calf_Raise', 'dumbbell', 'strength', 'intermediate', 'calves', ARRAY[]::text[]),
  ('Standing_Dumbbell_Press', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Standing_Dumbbell_Reverse_Curl', 'dumbbell', 'strength', 'intermediate', 'biceps', ARRAY['forearms']::text[]),
  ('Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY[]::text[]),
  ('Standing_Dumbbell_Triceps_Extension', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Standing_Dumbbell_Upright_Row', 'dumbbell', 'strength', 'beginner', 'traps', ARRAY['biceps','shoulders']::text[]),
  ('Standing_Elevated_Quad_Stretch', 'other', 'stretching', 'beginner', 'quadriceps', ARRAY[]::text[]),
  ('Standing_Front_Barbell_Raise_Over_Head', 'barbell', 'strength', 'intermediate', 'shoulders', ARRAY[]::text[]),
  ('Standing_Gastrocnemius_Calf_Stretch', NULL, 'stretching', 'beginner', 'calves', ARRAY['hamstrings']::text[]),
  ('Standing_Hamstring_and_Calf_Stretch', 'other', 'stretching', 'beginner', 'hamstrings', ARRAY[]::text[]),
  ('Standing_Hip_Circles', 'body only', 'stretching', 'beginner', 'abductors', ARRAY['adductors']::text[]),
  ('Standing_Hip_Flexors', NULL, 'stretching', 'beginner', 'quadriceps', ARRAY[]::text[]),
  ('Standing_Inner-Biceps_Curl', 'dumbbell', 'strength', 'intermediate', 'biceps', ARRAY[]::text[]),
  ('Standing_Leg_Curl', 'machine', 'strength', 'beginner', 'hamstrings', ARRAY[]::text[]),
  ('Standing_Long_Jump', 'body only', 'plyometrics', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Standing_Low-Pulley_Deltoid_Raise', 'cable', 'strength', 'beginner', 'shoulders', ARRAY['forearms']::text[]),
  ('Standing_Low-Pulley_One-Arm_Triceps_Extension', 'cable', 'strength', 'intermediate', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Standing_Military_Press', 'barbell', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Standing_Olympic_Plate_Hand_Squeeze', 'other', 'strength', 'beginner', 'forearms', ARRAY['biceps']::text[]),
  ('Standing_One-Arm_Cable_Curl', 'cable', 'strength', 'intermediate', 'biceps', ARRAY[]::text[]),
  ('Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Standing_One-Arm_Dumbbell_Triceps_Extension', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Standing_Overhead_Barbell_Triceps_Extension', 'barbell', 'strength', 'beginner', 'triceps', ARRAY['shoulders']::text[]),
  ('Standing_Palm-In_One-Arm_Dumbbell_Press', 'dumbbell', 'strength', 'beginner', 'shoulders', ARRAY['triceps']::text[]),
  ('Standing_Palms-In_Dumbbell_Press', 'dumbbell', 'strength', 'intermediate', 'shoulders', ARRAY['triceps']::text[]),
  ('Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl', 'barbell', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Standing_Rope_Crunch', 'cable', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Standing_Soleus_And_Achilles_Stretch', NULL, 'stretching', 'beginner', 'calves', ARRAY[]::text[]),
  ('Standing_Toe_Touches', NULL, 'stretching', 'beginner', 'hamstrings', ARRAY['calves']::text[]),
  ('Standing_Towel_Triceps_Extension', 'body only', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Standing_Two-Arm_Overhead_Throw', 'medicine ball', 'plyometrics', 'beginner', 'shoulders', ARRAY['chest','lats']::text[]),
  ('Star_Jump', 'body only', 'plyometrics', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings','shoulders']::text[]),
  ('Step_Mill', 'machine', 'cardio', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Step-up_with_Knee_Raise', 'body only', 'strength', 'beginner', 'glutes', ARRAY['hamstrings','quadriceps']::text[]),
  ('Stiff_Leg_Barbell_Good_Morning', 'barbell', 'strength', 'beginner', 'lower back', ARRAY['glutes','hamstrings']::text[]),
  ('Stiff-Legged_Barbell_Deadlift', 'barbell', 'strength', 'intermediate', 'hamstrings', ARRAY['glutes','lower back']::text[]),
  ('Stiff-Legged_Dumbbell_Deadlift', 'dumbbell', 'strength', 'beginner', 'hamstrings', ARRAY['glutes','lower back']::text[]),
  ('Stomach_Vacuum', 'body only', 'stretching', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Straight_Bar_Bench_Mid_Rows', 'barbell', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats']::text[]),
  ('Straight_Raises_on_Incline_Bench', 'barbell', 'strength', 'beginner', 'shoulders', ARRAY['traps']::text[]),
  ('Straight-Arm_Dumbbell_Pullover', 'dumbbell', 'strength', 'intermediate', 'chest', ARRAY['lats','shoulders','triceps']::text[]),
  ('Straight-Arm_Pulldown', 'cable', 'strength', 'beginner', 'lats', ARRAY[]::text[]),
  ('Stride_Jump_Crossover', 'other', 'plyometrics', 'beginner', 'quadriceps', ARRAY['abductors','adductors','calves','hamstrings']::text[]),
  ('Sumo_Deadlift', 'barbell', 'powerlifting', 'intermediate', 'hamstrings', ARRAY['adductors','forearms','glutes','lower back','middle back','quadriceps','traps']::text[]),
  ('Sumo_Deadlift_with_Bands', 'barbell', 'powerlifting', 'intermediate', 'hamstrings', ARRAY['adductors','forearms','glutes','lower back','middle back','quadriceps','traps']::text[]),
  ('Sumo_Deadlift_with_Chains', 'barbell', 'powerlifting', 'intermediate', 'hamstrings', ARRAY['abductors','adductors','forearms','glutes','lower back','middle back','quadriceps','traps']::text[]),
  ('Superman', 'body only', 'stretching', 'beginner', 'lower back', ARRAY['glutes','hamstrings']::text[]),
  ('Supine_Chest_Throw', 'medicine ball', 'plyometrics', 'beginner', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('Supine_One-Arm_Overhead_Throw', 'medicine ball', 'plyometrics', 'beginner', 'abdominals', ARRAY['chest','lats','shoulders']::text[]),
  ('Supine_Two-Arm_Overhead_Throw', 'medicine ball', 'plyometrics', 'beginner', 'abdominals', ARRAY['chest','lats','shoulders']::text[]),
  ('Suspended_Fallout', 'other', 'strength', 'intermediate', 'abdominals', ARRAY['chest','lower back','shoulders']::text[]),
  ('Svend_Press', 'other', 'strength', 'beginner', 'chest', ARRAY['forearms','shoulders','triceps']::text[]),
  ('T-Bar_Row_with_Handle', 'barbell', 'strength', 'beginner', 'middle back', ARRAY['biceps','lats']::text[]),
  ('Tate_Press', 'dumbbell', 'strength', 'intermediate', 'triceps', ARRAY['chest','shoulders']::text[]),
  ('The_Straddle', NULL, 'stretching', 'beginner', 'hamstrings', ARRAY['adductors','calves']::text[]),
  ('Thigh_Abductor', 'machine', 'strength', 'beginner', 'abductors', ARRAY['glutes']::text[]),
  ('Thigh_Adductor', 'machine', 'strength', 'beginner', 'adductors', ARRAY['glutes','hamstrings']::text[]),
  ('Toe_Touchers', 'body only', 'stretching', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Torso_Rotation', 'exercise ball', 'stretching', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Trail_Running_Walking', NULL, 'cardio', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Tricep_Dumbbell_Kickback', 'dumbbell', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Tricep_Side_Stretch', NULL, 'stretching', 'beginner', 'triceps', ARRAY['shoulders']::text[]),
  ('Triceps_Overhead_Extension_with_Rope', 'cable', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Triceps_Pushdown', 'cable', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Triceps_Pushdown_-_Rope_Attachment', 'cable', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Triceps_Pushdown_-_V-Bar_Attachment', 'cable', 'strength', 'beginner', 'triceps', ARRAY[]::text[]),
  ('Two-Arm_Dumbbell_Preacher_Curl', 'dumbbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Two-Arm_Kettlebell_Clean', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['calves','glutes','hamstrings','lower back','traps']::text[]),
  ('Two-Arm_Kettlebell_Jerk', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['calves','quadriceps','triceps']::text[]),
  ('Two-Arm_Kettlebell_Military_Press', 'kettlebells', 'strength', 'intermediate', 'shoulders', ARRAY['triceps']::text[]),
  ('Two-Arm_Kettlebell_Row', 'kettlebells', 'strength', 'intermediate', 'middle back', ARRAY['biceps','lats']::text[]),
  ('Underhand_Cable_Pulldowns', 'cable', 'strength', 'beginner', 'lats', ARRAY['biceps','middle back','shoulders']::text[]),
  ('Upper_Back-Leg_Grab', NULL, 'stretching', 'beginner', 'hamstrings', ARRAY['lower back','middle back']::text[]),
  ('Upright_Barbell_Row', 'barbell', 'strength', 'beginner', 'shoulders', ARRAY['traps']::text[]),
  ('Upright_Cable_Row', 'cable', 'strength', 'intermediate', 'traps', ARRAY['shoulders']::text[]),
  ('Upright_Row_-_With_Bands', 'bands', 'strength', 'beginner', 'traps', ARRAY['shoulders']::text[]),
  ('Upward_Stretch', NULL, 'stretching', 'beginner', 'shoulders', ARRAY['chest','lats']::text[]),
  ('V-Bar_Pulldown', 'cable', 'strength', 'intermediate', 'lats', ARRAY['biceps','middle back','shoulders']::text[]),
  ('V-Bar_Pullup', 'body only', 'strength', 'beginner', 'lats', ARRAY['biceps','middle back','shoulders']::text[]),
  ('Vertical_Swing', 'dumbbell', 'plyometrics', 'beginner', 'hamstrings', ARRAY['glutes','quadriceps','shoulders']::text[]),
  ('Walking_Treadmill', 'machine', 'cardio', 'beginner', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Weighted_Ball_Hyperextension', 'exercise ball', 'strength', 'intermediate', 'lower back', ARRAY['glutes','hamstrings','middle back']::text[]),
  ('Weighted_Ball_Side_Bend', 'exercise ball', 'strength', 'intermediate', 'abdominals', ARRAY[]::text[]),
  ('Weighted_Crunches', 'medicine ball', 'strength', 'beginner', 'abdominals', ARRAY[]::text[]),
  ('Weighted_Jump_Squat', 'barbell', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings','lower back']::text[]),
  ('Weighted_Pull_Ups', 'other', 'strength', 'intermediate', 'lats', ARRAY['biceps','middle back']::text[]),
  ('Weighted_Sit-Ups_-_With_Bands', 'other', 'strength', 'intermediate', 'abdominals', ARRAY[]::text[]),
  ('Wide_Stance_Barbell_Squat', 'barbell', 'strength', 'intermediate', 'quadriceps', ARRAY['calves','glutes','hamstrings','lower back']::text[]),
  ('Wide_Stance_Stiff_Legs', 'barbell', 'olympic weightlifting', 'intermediate', 'hamstrings', ARRAY['adductors','glutes','lower back']::text[]),
  ('Wide-Grip_Barbell_Bench_Press', 'barbell', 'strength', 'intermediate', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Wide-Grip_Decline_Barbell_Bench_Press', 'barbell', 'strength', 'intermediate', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Wide-Grip_Decline_Barbell_Pullover', 'barbell', 'strength', 'intermediate', 'chest', ARRAY['shoulders','triceps']::text[]),
  ('Wide-Grip_Lat_Pulldown', 'cable', 'strength', 'beginner', 'lats', ARRAY['biceps','middle back','shoulders']::text[]),
  ('Wide-Grip_Pulldown_Behind_The_Neck', 'cable', 'strength', 'intermediate', 'lats', ARRAY['biceps','middle back','shoulders']::text[]),
  ('Wide-Grip_Rear_Pull-Up', 'body only', 'strength', 'intermediate', 'lats', ARRAY['biceps','middle back','shoulders']::text[]),
  ('Wide-Grip_Standing_Barbell_Curl', 'barbell', 'strength', 'beginner', 'biceps', ARRAY[]::text[]),
  ('Windmills', NULL, 'stretching', 'intermediate', 'abductors', ARRAY['glutes','hamstrings','lower back']::text[]),
  ('Worlds_Greatest_Stretch', NULL, 'stretching', 'intermediate', 'hamstrings', ARRAY['calves','glutes','quadriceps']::text[]),
  ('Wrist_Roller', 'other', 'strength', 'beginner', 'forearms', ARRAY['shoulders']::text[]),
  ('Wrist_Rotations_with_Straight_Bar', 'barbell', 'strength', 'beginner', 'forearms', ARRAY[]::text[]),
  ('Yoke_Walk', 'other', 'strongman', 'intermediate', 'quadriceps', ARRAY['abdominals','abductors','adductors','calves','glutes','hamstrings','lower back']::text[]),
  ('Zercher_Squats', 'barbell', 'strength', 'expert', 'quadriceps', ARRAY['calves','glutes','hamstrings']::text[]),
  ('Zottman_Curl', 'dumbbell', 'strength', 'intermediate', 'biceps', ARRAY['forearms']::text[]),
  ('Zottman_Preacher_Curl', 'dumbbell', 'strength', 'intermediate', 'biceps', ARRAY['forearms']::text[])
) AS v(source_id, equipment, category, difficulty, target_muscle, secondary_muscles)
WHERE e.source = 'free-exercise-db' AND e.source_id = v.source_id;

-- Populate exercise_taxonomy from the now-enriched columns, so filter
-- dropdowns are data-driven instead of a hardcoded list in the mobile app.
INSERT INTO public.exercise_taxonomy (kind, value)
SELECT DISTINCT 'muscle', muscle_group FROM public.exercises WHERE muscle_group IS NOT NULL
UNION
SELECT DISTINCT 'body_part', body_part FROM public.exercises WHERE body_part IS NOT NULL
UNION
SELECT DISTINCT 'equipment', equipment FROM public.exercises WHERE equipment IS NOT NULL
UNION
SELECT DISTINCT 'category', category FROM public.exercises WHERE category IS NOT NULL
ON CONFLICT (kind, value) DO NOTHING;

-- ============================================================================
-- Favorites: new table, athlete-scoped, standard RLS pattern used everywhere
-- else in this schema (own-row-only via auth.uid()).
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.exercise_favorites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  exercise_id UUID NOT NULL REFERENCES public.exercises(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, exercise_id)
);

ALTER TABLE public.exercise_favorites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage their own favorites" ON public.exercise_favorites;
CREATE POLICY "Users manage their own favorites"
  ON public.exercise_favorites FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_exercise_favorites_user ON public.exercise_favorites(user_id);
