-- ============================================================================
-- 20260812133000_exercise_source_taxonomy_reconciliation.sql
-- ============================================================================
-- Reconciles public.exercises.source_type onto the canonical taxonomy:
--
--     yeti_first_party  Yeti-owned catalogue (V2 + V3 datasets)
--     legacy_catalog    externally sourced rows imported before the Yeti library
--     custom            coach-authored exercises
--
-- WHY THIS IS NOT A BLANKET UPDATE
--
-- The obvious "UPDATE ... SET source_type='yeti_first_party' WHERE
-- source_type='yeti_v2'" is unsafe: exercises.source_type carries
-- DEFAULT 'yeti_v2', so ANY row ever inserted without an explicit source_type
-- silently looks Yeti-owned. Existing source_type values are therefore treated
-- here as untrusted, and membership comes only from the checked-in datasets via
-- the manifest below (generated by scripts/generate_exercise_provenance.ts).
--
-- Dataset version is likewise NOT inferred from ID shape. V2 dataset ids are
-- not UUIDs ("yeti-ex-0001"), so the importer minted UUIDs for them: 365 live
-- rows carry the 00000000-0000-4000-a000-* shape while the V3 dataset holds
-- only 200 records. ID prefix proves nothing.
--
-- The manifest is keyed by slug, which is unique within each dataset and
-- already matches the live catalogue 1:1. Row ids are never rewritten, so
-- plan_exercises / session_sets / exercise history references stay intact.
--
-- Idempotent. No deletes. Aborts rather than guessing.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Canonical membership manifest (generated — do not hand-edit).
--    396 canonical exercises from 420 input records; 24 slugs appear in
--    both datasets and reconcile to a single row.
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE _yeti_canonical (
  slug             text PRIMARY KEY,
  dataset_versions text NOT NULL,
  -- Which dataset supplies this exercise's CONTENT. Recorded so provenance is
  -- deterministic instead of depending on import order; see
  -- scripts/generate_exercise_provenance.ts for the reviewed decision.
  merge_winner     text NOT NULL
) ON COMMIT DROP;

INSERT INTO _yeti_canonical (slug, dataset_versions, merge_winner) VALUES
  ('90-90-hip-switch', 'v2', 'v2'),
  ('ab-wheel-rollout', 'v2', 'v2'),
  ('ab-wheel-rollout-from-knees', 'v3', 'v3'),
  ('adductor-rock-back', 'v2', 'v2'),
  ('air-bike-sprint', 'v2,v3', 'v3'),
  ('air-bike-tempo-ride', 'v3', 'v3'),
  ('alternating-dumbbell-bench-press', 'v3', 'v3'),
  ('alternating-dumbbell-curl', 'v2', 'v2'),
  ('ankle-dorsiflexion-mobilization', 'v2', 'v2'),
  ('arnold-press', 'v2', 'v2'),
  ('assault-runner-tempo-run', 'v3', 'v3'),
  ('assisted-pull-up', 'v2', 'v2'),
  ('assisted-sissy-squat', 'v3', 'v3'),
  ('b-stance-hip-thrust', 'v3', 'v3'),
  ('back-squat', 'v2', 'v2'),
  ('backward-sled-drag', 'v3', 'v3'),
  ('band-shoulder-dislocate', 'v2', 'v2'),
  ('barbell-bench-press', 'v2', 'v2'),
  ('barbell-bent-over-row', 'v2', 'v2'),
  ('barbell-curl', 'v2', 'v2'),
  ('barbell-glute-bridge', 'v3', 'v3'),
  ('barbell-overhead-press', 'v2', 'v2'),
  ('barbell-romanian-deadlift-from-blocks', 'v3', 'v3'),
  ('barbell-seal-row', 'v3', 'v3'),
  ('barbell-upright-row', 'v2', 'v2'),
  ('barbell-z-press', 'v3', 'v3'),
  ('battle-rope-alternating-waves', 'v3', 'v3'),
  ('battle-rope-slams', 'v3', 'v3'),
  ('bayesian-cable-curl', 'v2', 'v2'),
  ('behind-the-body-cable-lateral-raise', 'v2,v3', 'v3'),
  ('belt-squat', 'v2', 'v2'),
  ('belt-squat-calf-raise', 'v3', 'v3'),
  ('belt-squat-machine', 'v3', 'v3'),
  ('bent-knee-calf-raise', 'v3', 'v3'),
  ('bent-over-dumbbell-reverse-fly', 'v2', 'v2'),
  ('bird-dog', 'v2', 'v2'),
  ('bodyweight-tibialis-raise', 'v2', 'v2'),
  ('box-squat', 'v2', 'v2'),
  ('bulgarian-split-squat', 'v2', 'v2'),
  ('cable-anti-extension-walkout', 'v3', 'v3'),
  ('cable-bayesian-hammer-curl', 'v3', 'v3'),
  ('cable-belt-squat', 'v3', 'v3'),
  ('cable-chest-press', 'v2', 'v2'),
  ('cable-crossover-hold', 'v3', 'v3'),
  ('cable-crunch', 'v2', 'v2'),
  ('cable-curl', 'v2', 'v2'),
  ('cable-dead-bug', 'v3', 'v3'),
  ('cable-front-raise', 'v2', 'v2'),
  ('cable-front-raise-with-rope', 'v3', 'v3'),
  ('cable-glute-kickback', 'v2,v3', 'v3'),
  ('cable-high-to-low-fly', 'v2', 'v2'),
  ('cable-hip-abduction', 'v3', 'v3'),
  ('cable-kickback', 'v2', 'v2'),
  ('cable-kneeling-crunch', 'v3', 'v3'),
  ('cable-lat-prayer', 'v3', 'v3'),
  ('cable-lateral-raise', 'v2', 'v2'),
  ('cable-lift', 'v2', 'v2'),
  ('cable-lift-low-to-high', 'v3', 'v3'),
  ('cable-low-to-high-fly', 'v2', 'v2'),
  ('cable-lying-leg-curl', 'v3', 'v3'),
  ('cable-mid-fly', 'v2', 'v2'),
  ('cable-press-around', 'v3', 'v3'),
  ('cable-pull-through', 'v2,v3', 'v3'),
  ('cable-pushdown', 'v2', 'v2'),
  ('cable-rear-delt-fly', 'v2', 'v2'),
  ('cable-rear-delt-sweep', 'v3', 'v3'),
  ('cable-reverse-lunge', 'v3', 'v3'),
  ('cable-seated-row', 'v2', 'v2'),
  ('cable-shoulder-press', 'v2', 'v2'),
  ('cable-skull-crusher', 'v3', 'v3'),
  ('cable-spider-curl', 'v3', 'v3'),
  ('cable-standing-calf-raise', 'v3', 'v3'),
  ('cable-standing-crunch', 'v3', 'v3'),
  ('cable-standing-leg-curl', 'v3', 'v3'),
  ('cable-svend-press', 'v3', 'v3'),
  ('cable-upright-row', 'v2', 'v2'),
  ('cable-wood-chop', 'v2', 'v2'),
  ('cable-wood-chop-high-to-low', 'v3', 'v3'),
  ('cable-y-raise', 'v2,v3', 'v3'),
  ('captain-chair-knee-raise', 'v2', 'v2'),
  ('captain-chair-leg-raise', 'v3', 'v3'),
  ('cat-cow', 'v2', 'v2'),
  ('chest-supported-dumbbell-rear-delt-raise', 'v3', 'v3'),
  ('chest-supported-dumbbell-row', 'v2', 'v2'),
  ('chest-supported-t-bar-row', 'v2,v3', 'v3'),
  ('childs-pose-lat-stretch', 'v2', 'v2'),
  ('chin-up', 'v2', 'v2'),
  ('close-grip-bench-press', 'v2', 'v2'),
  ('close-grip-incline-barbell-press', 'v3', 'v3'),
  ('close-grip-smith-machine-press', 'v3', 'v3'),
  ('concentration-curl', 'v2', 'v2'),
  ('conventional-deadlift', 'v2', 'v2'),
  ('converging-incline-chest-press', 'v3', 'v3'),
  ('couch-stretch', 'v2', 'v2'),
  ('cross-body-cable-extension', 'v2', 'v2'),
  ('cross-body-cable-lat-pulldown', 'v3', 'v3'),
  ('cross-body-cable-triceps-extension', 'v3', 'v3'),
  ('cross-body-dumbbell-hammer-curl', 'v3', 'v3'),
  ('cross-body-hammer-curl', 'v2', 'v2'),
  ('cross-body-lat-pulldown', 'v2', 'v2'),
  ('cross-body-rear-delt-cable-fly', 'v3', 'v3'),
  ('cuffed-cable-glute-kickback', 'v3', 'v3'),
  ('cuffed-cable-lateral-raise', 'v3', 'v3'),
  ('curtsy-cable-lunge', 'v3', 'v3'),
  ('curved-treadmill-sprint', 'v3', 'v3'),
  ('cyclist-back-squat', 'v3', 'v3'),
  ('dead-bug', 'v2', 'v2'),
  ('decline-barbell-bench-press', 'v2', 'v2'),
  ('decline-cable-crunch', 'v3', 'v3'),
  ('decline-dumbbell-press', 'v2,v3', 'v3'),
  ('decline-machine-chest-press', 'v2', 'v2'),
  ('decline-sit-up', 'v2', 'v2'),
  ('deep-squat-hold', 'v2', 'v2'),
  ('deficit-calf-raise', 'v3', 'v3'),
  ('diverging-chest-press', 'v2', 'v2'),
  ('donkey-calf-raise', 'v2', 'v2'),
  ('donkey-calf-raise-machine', 'v3', 'v3'),
  ('dumbbell-bench-press', 'v2', 'v2'),
  ('dumbbell-curl', 'v2', 'v2'),
  ('dumbbell-front-raise', 'v2', 'v2'),
  ('dumbbell-hex-press', 'v3', 'v3'),
  ('dumbbell-lateral-raise', 'v2', 'v2'),
  ('dumbbell-lying-leg-curl', 'v3', 'v3'),
  ('dumbbell-pullover', 'v2', 'v2'),
  ('dumbbell-pullover-press', 'v3', 'v3'),
  ('dumbbell-romanian-deadlift', 'v2', 'v2'),
  ('dumbbell-row', 'v2', 'v2'),
  ('dumbbell-scaption-raise', 'v3', 'v3'),
  ('dumbbell-seal-row', 'v3', 'v3'),
  ('dumbbell-shoulder-press', 'v2', 'v2'),
  ('dumbbell-skull-crusher', 'v2', 'v2'),
  ('dumbbell-squeeze-press', 'v2', 'v2'),
  ('dumbbell-staggered-stance-romanian-deadlift', 'v3', 'v3'),
  ('dumbbell-step-down', 'v3', 'v3'),
  ('dumbbell-y-raise', 'v2', 'v2'),
  ('elliptical-trainer', 'v2', 'v2'),
  ('ez-bar-curl', 'v2', 'v2'),
  ('ez-bar-drag-curl', 'v3', 'v3'),
  ('ez-bar-floor-skull-crusher', 'v3', 'v3'),
  ('ez-bar-skull-crusher', 'v2', 'v2'),
  ('face-pull', 'v2', 'v2'),
  ('farmer-walk-on-toes', 'v3', 'v3'),
  ('farmers-carry', 'v3', 'v3'),
  ('forty-five-degree-hip-extension-glute-bias', 'v3', 'v3'),
  ('forty-five-degree-hip-extension-hamstring-bias', 'v3', 'v3'),
  ('forward-lunge', 'v2', 'v2'),
  ('forward-sled-drag', 'v3', 'v3'),
  ('frog-pump', 'v3', 'v3'),
  ('front-foot-elevated-split-squat', 'v3', 'v3'),
  ('front-plank', 'v2', 'v2'),
  ('front-rack-kettlebell-carry', 'v3', 'v3'),
  ('front-squat', 'v2', 'v2'),
  ('glute-ham-developer-curl', 'v3', 'v3'),
  ('glute-ham-raise', 'v2', 'v2'),
  ('glute-kickback-machine', 'v2', 'v2'),
  ('goblet-squat', 'v2', 'v2'),
  ('good-morning', 'v2', 'v2'),
  ('good-morning-to-pins', 'v3', 'v3'),
  ('guillotine-press', 'v3', 'v3'),
  ('hack-squat', 'v2', 'v2'),
  ('hack-squat-calf-raise', 'v3', 'v3'),
  ('half-kneeling-hip-flexor-stretch', 'v2', 'v2'),
  ('half-kneeling-landmine-press', 'v3', 'v3'),
  ('half-kneeling-pallof-press', 'v3', 'v3'),
  ('half-kneeling-single-arm-lat-pulldown', 'v3', 'v3'),
  ('half-kneeling-single-arm-pulldown', 'v2', 'v2'),
  ('hammer-curl', 'v2', 'v2'),
  ('hammer-grip-chest-press', 'v2', 'v2'),
  ('hammer-strength-row', 'v2', 'v2'),
  ('hanging-knee-raise', 'v2,v3', 'v3'),
  ('hanging-leg-raise', 'v2', 'v2'),
  ('heavy-sled-push', 'v3', 'v3'),
  ('heels-elevated-goblet-squat', 'v3', 'v3'),
  ('high-cable-biceps-curl', 'v3', 'v3'),
  ('high-cable-row', 'v2', 'v2'),
  ('high-foot-leg-press', 'v3', 'v3'),
  ('high-row-machine', 'v2', 'v2'),
  ('high-step-up-glute-bias', 'v3', 'v3'),
  ('hip-abduction-machine', 'v2', 'v2'),
  ('hip-adduction-machine', 'v2', 'v2'),
  ('hip-thrust', 'v2', 'v2'),
  ('horizontal-leg-press', 'v2', 'v2'),
  ('incline-barbell-bench-press', 'v2', 'v2'),
  ('incline-bench-dumbbell-row', 'v3', 'v3'),
  ('incline-dumbbell-curl', 'v2,v3', 'v3'),
  ('incline-dumbbell-lateral-raise', 'v3', 'v3'),
  ('incline-dumbbell-press', 'v2', 'v2'),
  ('incline-dumbbell-squeeze-press', 'v3', 'v3'),
  ('incline-dumbbell-triceps-extension', 'v3', 'v3'),
  ('incline-machine-chest-press', 'v2', 'v2'),
  ('incline-treadmill-walk', 'v2,v3', 'v3'),
  ('iso-lateral-chest-press', 'v2', 'v2'),
  ('iso-lateral-incline-press', 'v2', 'v2'),
  ('iso-lateral-low-row', 'v3', 'v3'),
  ('iso-lateral-machine-row', 'v2', 'v2'),
  ('iso-lateral-shoulder-press', 'v2', 'v2'),
  ('isometric-calf-raise-hold', 'v3', 'v3'),
  ('jm-press', 'v2', 'v2'),
  ('kettlebell-swing', 'v2', 'v2'),
  ('kneeling-cable-chest-press', 'v3', 'v3'),
  ('kneeling-rope-crunch', 'v2', 'v2'),
  ('kneeling-rope-pullover', 'v3', 'v3'),
  ('landmine-front-squat', 'v3', 'v3'),
  ('landmine-meadows-row', 'v3', 'v3'),
  ('landmine-press', 'v2', 'v2'),
  ('landmine-reverse-lunge', 'v3', 'v3'),
  ('landmine-rotation', 'v3', 'v3'),
  ('landmine-row', 'v2', 'v2'),
  ('lat-pulldown', 'v2', 'v2'),
  ('lateral-lunge', 'v2', 'v2'),
  ('lateral-sled-drag', 'v3', 'v3'),
  ('leaning-cable-lateral-raise', 'v2,v3', 'v3'),
  ('leaning-dumbbell-lateral-raise', 'v2', 'v2'),
  ('leg-extension', 'v2', 'v2'),
  ('leg-press', 'v2', 'v2'),
  ('leg-press-calf-press', 'v3', 'v3'),
  ('leg-press-calf-raise', 'v2', 'v2'),
  ('leverage-squat', 'v3', 'v3'),
  ('linear-hack-squat', 'v2,v3', 'v3'),
  ('long-stride-bulgarian-split-squat', 'v3', 'v3'),
  ('low-cable-row', 'v2', 'v2'),
  ('low-foot-leg-press', 'v3', 'v3'),
  ('low-row-machine', 'v2', 'v2'),
  ('lying-leg-curl', 'v2', 'v2'),
  ('lying-single-leg-curl', 'v3', 'v3'),
  ('machine-abdominal-crunch', 'v2,v3', 'v3'),
  ('machine-chest-press', 'v2', 'v2'),
  ('machine-glute-drive', 'v2', 'v2'),
  ('machine-lateral-raise', 'v2', 'v2'),
  ('machine-overhead-press-neutral-grip', 'v3', 'v3'),
  ('machine-preacher-curl', 'v2', 'v2'),
  ('machine-seated-row', 'v2', 'v2'),
  ('machine-shoulder-press', 'v2', 'v2'),
  ('machine-sissy-squat', 'v3', 'v3'),
  ('machine-triceps-extension', 'v3', 'v3'),
  ('meadows-row', 'v2', 'v2'),
  ('multi-hip-machine-extension', 'v3', 'v3'),
  ('narrow-stance-leg-press', 'v3', 'v3'),
  ('neutral-grip-chest-supported-row', 'v3', 'v3'),
  ('neutral-grip-lat-pulldown', 'v2', 'v2'),
  ('neutral-grip-machine-chest-press', 'v3', 'v3'),
  ('neutral-grip-machine-row', 'v2', 'v2'),
  ('neutral-grip-pull-up', 'v2', 'v2'),
  ('nordic-curl-machine', 'v3', 'v3'),
  ('nordic-hamstring-curl', 'v2', 'v2'),
  ('offset-farmer-carry', 'v3', 'v3'),
  ('overhead-cable-rope-extension', 'v3', 'v3'),
  ('overhead-dumbbell-extension', 'v2', 'v2'),
  ('overhead-rope-extension', 'v2', 'v2'),
  ('pallof-hold', 'v2', 'v2'),
  ('pallof-press', 'v2,v3', 'v3'),
  ('pallof-press-iso-hold', 'v3', 'v3'),
  ('paused-calf-raise', 'v3', 'v3'),
  ('pec-deck-fly', 'v2', 'v2'),
  ('pendlay-row', 'v2', 'v2'),
  ('pendulum-squat', 'v2', 'v2'),
  ('plate-front-raise', 'v2', 'v2'),
  ('plate-loaded-decline-chest-press', 'v3', 'v3'),
  ('plate-loaded-high-row', 'v3', 'v3'),
  ('plate-loaded-hip-thrust', 'v3', 'v3'),
  ('plate-loaded-low-row', 'v3', 'v3'),
  ('plate-loaded-shoulder-press', 'v3', 'v3'),
  ('pogo-jump', 'v3', 'v3'),
  ('preacher-curl', 'v2', 'v2'),
  ('preacher-curl-machine', 'v3', 'v3'),
  ('pull-up', 'v2', 'v2'),
  ('rack-pull', 'v2', 'v2'),
  ('reverse-crunch', 'v2', 'v2'),
  ('reverse-crunch-on-bench', 'v3', 'v3'),
  ('reverse-grip-barbell-bench-press', 'v3', 'v3'),
  ('reverse-grip-cable-curl', 'v3', 'v3'),
  ('reverse-grip-cable-pushdown', 'v3', 'v3'),
  ('reverse-grip-pushdown', 'v2', 'v2'),
  ('reverse-grip-seated-cable-row', 'v3', 'v3'),
  ('reverse-hack-squat', 'v3', 'v3'),
  ('reverse-hyperextension', 'v2', 'v2'),
  ('reverse-hyperextension-hamstring-bias', 'v3', 'v3'),
  ('reverse-lunge', 'v2', 'v2'),
  ('reverse-pec-deck', 'v2', 'v2'),
  ('reverse-pec-deck-hold', 'v3', 'v3'),
  ('romanian-deadlift', 'v2', 'v2'),
  ('rope-hammer-curl', 'v2,v3', 'v3'),
  ('rope-pullover', 'v2', 'v2'),
  ('rope-pushdown', 'v2', 'v2'),
  ('rope-seated-cable-row', 'v3', 'v3'),
  ('row-erg-sprint', 'v3', 'v3'),
  ('row-erg-steady-state', 'v3', 'v3'),
  ('rowing-ergometer', 'v2', 'v2'),
  ('safety-bar-box-squat', 'v3', 'v3'),
  ('safety-bar-good-morning', 'v3', 'v3'),
  ('safety-bar-squat', 'v2', 'v2'),
  ('sandbag-bear-hug-carry', 'v3', 'v3'),
  ('seal-row', 'v2', 'v2'),
  ('seated-arnold-press', 'v3', 'v3'),
  ('seated-barbell-shoulder-press', 'v2', 'v2'),
  ('seated-calf-raise', 'v2', 'v2'),
  ('seated-calf-raise-machine', 'v3', 'v3'),
  ('seated-dumbbell-lateral-raise', 'v2', 'v2'),
  ('seated-hip-abduction-back-lean', 'v3', 'v3'),
  ('seated-hip-abduction-forward-lean', 'v3', 'v3'),
  ('seated-leg-curl', 'v2', 'v2'),
  ('seated-single-leg-curl', 'v3', 'v3'),
  ('seated-soleus-raise-with-dumbbell', 'v3', 'v3'),
  ('seated-tibialis-raise', 'v3', 'v3'),
  ('side-plank', 'v2', 'v2'),
  ('single-arm-cable-chest-press', 'v2', 'v2'),
  ('single-arm-cable-fly', 'v2', 'v2'),
  ('single-arm-cable-pushdown', 'v2,v3', 'v3'),
  ('single-arm-cable-row', 'v2', 'v2'),
  ('single-arm-landmine-press', 'v2', 'v2'),
  ('single-arm-lat-pulldown', 'v2', 'v2'),
  ('single-arm-machine-high-row', 'v3', 'v3'),
  ('single-arm-machine-shoulder-press', 'v3', 'v3'),
  ('single-arm-overhead-cable-extension', 'v2,v3', 'v3'),
  ('single-arm-overhead-dumbbell-extension', 'v2', 'v2'),
  ('single-arm-preacher-curl-machine', 'v3', 'v3'),
  ('single-arm-rear-delt-cable-sweep', 'v2', 'v2'),
  ('single-arm-seated-chest-press', 'v3', 'v3'),
  ('single-leg-calf-raise', 'v2', 'v2'),
  ('single-leg-curl', 'v2', 'v2'),
  ('single-leg-dumbbell-calf-raise', 'v3', 'v3'),
  ('single-leg-extension', 'v2', 'v2'),
  ('single-leg-hip-thrust', 'v3', 'v3'),
  ('single-leg-horizontal-leg-press', 'v3', 'v3'),
  ('single-leg-landmine-romanian-deadlift', 'v3', 'v3'),
  ('single-leg-press', 'v2', 'v2'),
  ('single-leg-romanian-deadlift', 'v2', 'v2'),
  ('sissy-squat-machine', 'v2', 'v2'),
  ('ski-erg-sprint', 'v3', 'v3'),
  ('ski-erg-steady-state', 'v3', 'v3'),
  ('ski-ergometer', 'v2', 'v2'),
  ('sled-pull', 'v2', 'v2'),
  ('sled-push', 'v2,v3', 'v3'),
  ('slider-leg-curl', 'v3', 'v3'),
  ('smith-machine-bench-press', 'v2', 'v2'),
  ('smith-machine-calf-raise', 'v2', 'v2'),
  ('smith-machine-decline-press', 'v2,v3', 'v3'),
  ('smith-machine-floor-press', 'v3', 'v3'),
  ('smith-machine-front-squat', 'v2', 'v2'),
  ('smith-machine-hip-thrust', 'v2,v3', 'v3'),
  ('smith-machine-incline-press', 'v2', 'v2'),
  ('smith-machine-reverse-lunge', 'v3', 'v3'),
  ('smith-machine-romanian-deadlift', 'v3', 'v3'),
  ('smith-machine-shoulder-press', 'v2,v3', 'v3'),
  ('smith-machine-split-squat', 'v2,v3', 'v3'),
  ('smith-machine-squat', 'v2', 'v2'),
  ('smith-machine-standing-calf-raise', 'v3', 'v3'),
  ('smith-machine-upright-row', 'v3', 'v3'),
  ('spider-curl', 'v2', 'v2'),
  ('split-stance-single-arm-cable-press', 'v3', 'v3'),
  ('stability-ball-crunch', 'v2', 'v2'),
  ('stability-ball-rollout', 'v3', 'v3'),
  ('stair-climber', 'v2', 'v2'),
  ('stair-climber-step', 'v3', 'v3'),
  ('standing-cable-chest-press', 'v3', 'v3'),
  ('standing-cable-hip-abduction', 'v2', 'v2'),
  ('standing-cable-hip-adduction', 'v2', 'v2'),
  ('standing-cable-press-around', 'v2', 'v2'),
  ('standing-calf-raise', 'v2', 'v2'),
  ('standing-calf-raise-machine', 'v3', 'v3'),
  ('standing-hip-abduction-machine', 'v3', 'v3'),
  ('standing-leg-curl', 'v2', 'v2'),
  ('standing-machine-hip-extension', 'v3', 'v3'),
  ('standing-machine-leg-curl', 'v3', 'v3'),
  ('standing-single-leg-calf-raise', 'v3', 'v3'),
  ('stationary-bike', 'v2', 'v2'),
  ('step-up', 'v2', 'v2'),
  ('stiff-leg-deadlift', 'v2', 'v2'),
  ('straight-arm-pulldown', 'v2', 'v2'),
  ('straight-arm-rope-pulldown', 'v3', 'v3'),
  ('suitcase-carry', 'v3', 'v3'),
  ('sumo-deadlift', 'v2', 'v2'),
  ('swiss-ball-leg-curl', 'v3', 'v3'),
  ('t-bar-row', 'v2', 'v2'),
  ('thoracic-open-book', 'v2', 'v2'),
  ('tibialis-bar-raise', 'v3', 'v3'),
  ('tibialis-raise', 'v2', 'v2'),
  ('trap-bar-bent-over-row', 'v3', 'v3'),
  ('trap-bar-deadlift', 'v2', 'v2'),
  ('trap-bar-romanian-deadlift', 'v3', 'v3'),
  ('treadmill-run', 'v2', 'v2'),
  ('two-hand-landmine-press', 'v3', 'v3'),
  ('underhand-barbell-row', 'v2', 'v2'),
  ('underhand-lat-pulldown', 'v2', 'v2'),
  ('v-squat', 'v2', 'v2'),
  ('v-squat-machine', 'v3', 'v3'),
  ('vertical-leg-press', 'v2', 'v2'),
  ('walking-lunge', 'v2', 'v2'),
  ('wall-slide', 'v2', 'v2'),
  ('wall-supported-tibialis-raise', 'v3', 'v3'),
  ('weighted-decline-sit-up', 'v3', 'v3'),
  ('wide-grip-cable-row', 'v2,v3', 'v3'),
  ('wide-grip-lat-pulldown', 'v2', 'v2'),
  ('wide-grip-machine-row', 'v2,v3', 'v3'),
  ('worlds-greatest-stretch', 'v2', 'v2'),
  ('zercher-squat', 'v2', 'v2');

-- Fail loudly if the embedded manifest is not the expected size.
DO $$
DECLARE v_n pg_catalog.int4;
BEGIN
  SELECT pg_catalog.count(*) INTO v_n FROM _yeti_canonical;
  IF v_n <> 396 THEN
    RAISE EXCEPTION 'Manifest size % does not match expected 396', v_n;
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 2. Pre-flight: every canonical slug must exist exactly once live.
--    If the catalogue has drifted, stop rather than mislabel anything.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  v_missing pg_catalog.int4;
  v_dupes   pg_catalog.int4;
BEGIN
  SELECT pg_catalog.count(*) INTO v_missing
  FROM _yeti_canonical c
  WHERE NOT EXISTS (SELECT 1 FROM public.exercises e WHERE e.slug = c.slug);

  SELECT pg_catalog.count(*) INTO v_dupes
  FROM (
    SELECT e.slug FROM public.exercises e
    JOIN _yeti_canonical c ON c.slug = e.slug
    GROUP BY e.slug HAVING pg_catalog.count(*) > 1
  ) d;

  IF v_missing > 0 THEN
    RAISE EXCEPTION 'Aborting: % canonical slug(s) absent from public.exercises', v_missing;
  END IF;
  IF v_dupes > 0 THEN
    RAISE EXCEPTION 'Aborting: % canonical slug(s) duplicated in public.exercises', v_dupes;
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 3. Classify. Manifest membership wins; coach authorship is the only other
--    positive signal; everything else is legacy. Ids are never touched.
-- ---------------------------------------------------------------------------

-- 3a. Manifest-proven Yeti rows.
UPDATE public.exercises e
SET source_type = 'yeti_first_party'
FROM _yeti_canonical c
WHERE e.slug = c.slug
  AND e.created_by_coach_id IS NULL
  AND e.source_type IS DISTINCT FROM 'yeti_first_party';

-- 3b. Coach-authored rows are custom, whatever their inherited source_type
--     says. Checked after 3a so a coach copy of a catalogue slug stays custom.
UPDATE public.exercises
SET source_type = 'custom'
WHERE created_by_coach_id IS NOT NULL
  AND source_type IS DISTINCT FROM 'custom';

-- 3c. Everything else is legacy catalogue. This is the branch that repairs
--     rows which merely inherited the 'yeti_v2' DEFAULT.
UPDATE public.exercises e
SET source_type = 'legacy_catalog'
WHERE e.created_by_coach_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM _yeti_canonical c WHERE c.slug = e.slug)
  AND e.source_type IS DISTINCT FROM 'legacy_catalog';

-- ---------------------------------------------------------------------------
-- 4. Dataset provenance into metadata, from explicit membership only.
--    Stored as a JSON array so a shared slug records ["v2","v3"].
-- ---------------------------------------------------------------------------
UPDATE public.exercises e
SET metadata = COALESCE(e.metadata, '{}'::jsonb)
             || jsonb_build_object(
                  'dataset_version',
                  (SELECT jsonb_agg(v ORDER BY v)
                   FROM pg_catalog.unnest(pg_catalog.string_to_array(c.dataset_versions, ',')) AS v),
                  -- Which dataset owns the content, so a later re-import is
                  -- deterministic rather than order-dependent.
                  'content_source', pg_catalog.to_jsonb(c.merge_winner)
                )
FROM _yeti_canonical c
WHERE e.slug = c.slug;

-- Legacy/custom rows must not carry a Yeti dataset_version claim.
UPDATE public.exercises e
SET metadata = e.metadata - 'dataset_version' - 'content_source'
WHERE e.source_type <> 'yeti_first_party'
  AND e.metadata ? 'dataset_version';

-- ---------------------------------------------------------------------------
-- 5. Stop the contamination at source: the DEFAULT is what let unrelated rows
--    inherit Yeti provenance in the first place.
-- ---------------------------------------------------------------------------
ALTER TABLE public.exercises ALTER COLUMN source_type SET DEFAULT 'legacy_catalog';

-- ---------------------------------------------------------------------------
-- 6. Constrain the vocabulary — but only after proving nothing falls outside
--    it, so the migration reports the offending values instead of a bare
--    constraint violation.
-- ---------------------------------------------------------------------------
DO $$
DECLARE v_bad pg_catalog.text;
BEGIN
  SELECT pg_catalog.string_agg(DISTINCT COALESCE(source_type, '<NULL>'), ', ')
  INTO v_bad
  FROM public.exercises
  WHERE source_type IS NULL
     OR source_type NOT IN ('yeti_first_party', 'legacy_catalog', 'custom');

  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION 'Aborting: unclassified source_type value(s) remain: %', v_bad;
  END IF;
END $$;

ALTER TABLE public.exercises DROP CONSTRAINT IF EXISTS exercises_source_type_check;
ALTER TABLE public.exercises
  ADD CONSTRAINT exercises_source_type_check
  CHECK (source_type IN ('yeti_first_party', 'legacy_catalog', 'custom'));

COMMIT;
